### ISSUE TITLE
libp2p数组越界，崩溃

### ISSUE THREAD

**Issue by wchh** [33cn/chain33#1000]
panic: runtime error: slice bounds out of range [:826] with capacity 512
    2
    3 goroutine 9921985 [running]:
    4 github.com/libp2p/go-msgio.(*reader).ReadMsg(0xc00c5d44c0, 0x0, 0x0, 0x0, 0x0, 0x0)
    5         D:/goWork/pkg/mod/github.com/libp2p/go-msgio@v0.0.6/msgio.go:235 +0x2dc
    6 github.com/libp2p/go-libp2p-secio.(*etmReader).fill(0xc0052e34a0, 0x1de, 0x0)
    7         D:/goWork/pkg/mod/github.com/libp2p/go-libp2p-secio@v0.2.2/rw.go:132 +0x3f
    8 github.com/libp2p/go-libp2p-secio.(*etmReader).Read(0xc0052e34a0, 0xc00c525cd0, 0xc, 0xc, 0x0, 0x0, 0x0)
    9         D:/goWork/pkg/mod/github.com/libp2p/go-libp2p-secio@v0.2.2/rw.go:171 +0x2a5
   10 io.ReadAtLeast(0x2a09e810, 0xc003127000, 0xc00c525cd0, 0xc, 0xc, 0xc, 0xc, 0x0, 0x0)
   11         C:/Go/src/io/io.go:310 +0x8e
   12 io.ReadFull(...)
   13         C:/Go/src/io/io.go:329
   14 github.com/libp2p/go-yamux.(*Session).recvLoop(0xc000131ce0, 0x0, 0x0)
   15         D:/goWork/pkg/mod/github.com/libp2p/go-yamux@v1.3.7/session.go:526 +0xe1
   16 github.com/libp2p/go-yamux.(*Session).recv(0xc000131ce0)
   17         D:/goWork/pkg/mod/github.com/libp2p/go-yamux@v1.3.7/session.go:505 +0x32
   18 created by github.com/libp2p/go-yamux.newSession
   19         D:/goWork/pkg/mod/github.com/libp2p/go-yamux@v1.3.7/session.go:125 +0x380
   20 panic: runtime error: slice bounds out of range [:2158] with capacity 2048

**Comment by libangzhu** [comment]
这个是数据读取到buf中，并越界了。先确认下有没有存在多个goroutine同时对某个stream流进行读或者写，很有可能是这个问题导致的

**Comment by yann-sjtu** [comment]
老版本libp2p的bug
https://github.com/libp2p/go-libp2p/issues/1108
