### ISSUE TITLE
blockchain txCache实现问题

### ISSUE THREAD

**Issue by bysomeone** [33cn/chain33#1003]
blockchain txCache主要用于txHeight场景下查重，缓存一定区块区间所有交易的哈希，目前实现有以下几个问题

1. 在txHeight功能不打开情况下，不需要维护该缓存
2. 内存开销双倍，目前实现内存开销是实际交易哈希的双倍
3. 未处理区块回滚情况，区块回滚时，需要将属于当前区间的历史区块内的交易重新加入缓存

**Comment by vipwzw** [comment]
cache 采用 hash的一半把，16字节，这样冲突的概率也是非常低的，还可以减少一半的内容。
