### ISSUE TITLE
./test.sh

### ISSUE THREAD

**Issue by luo-xiaodong** [33cn/chain33#101]
{
    "isOK": false,
    "msg": "ErrSeedWordNum"
}
{
    "isOK": false,
    "msg": "ErrSaveSeedFirst"
}
ErrWalletIsLocked
ErrWalletIsLocked
ErrAccountNotExist

**Comment by luo-xiaodong** [comment]
钱包怎么锁解不了

**Comment by 33cn** [comment]
要先导入seed 才能正常使用钱包

**Comment by luo-xiaodong** [comment]
# 生成随机数种子，建议可以手工生成并保存好，后继可以使用此种子恢复钱包
seed=$(./chain33-cli seed generate -l 0 | jq '"seed":')

按这个文档操作出错
jq: error: syntax error, unexpected ':', expecting $end (Unix shell quoting issues?) at <top-level>, line 1:
"seed":      
jq: 1 compile error

是否可以修改成 **seed=$(./chain33-cli seed generate -l 0)**

这样试了 导入后提示解锁不了

**Comment by vipwzw** [comment]
@icehawk-hyb  错误提示可以稍微好一点。

@andyYuanFZM  看一下文档，是不是有问题。

@luo-xiaodong 提供一下你操作系统的版本

**Comment by vipwzw** [comment]
其实，手工复制一下也不难。

**Comment by vipwzw** [comment]
不需要jq

**Comment by luo-xiaodong** [comment]
系统 centos 7

**Comment by 33cn** [comment]
@icehawk-hyb  考虑后面版本 seed generate 直接返回 seed 内容，不要用json
muscle secret lamp decade crane peace rigid click virus decade patch possible vital current frozen

**Comment by 33cn** [comment]
这样就比较好处理了

**Comment by vipwzw** [comment]
```
kingdeMacBook-Pro:build kingwang$ ./chain33-cli seed save -s "muscle secret lamp decade crane peace rigid click virus decade patch possible vital current frozen" -p 123456
{
    "isOK": true,
    "msg": ""
}
kingdeMacBook-Pro:build kingwang$ ./chain33-cli wallet unlock -p 123456
{
    "isOK": true,
    "msg": ""
}

```

**Comment by vipwzw** [comment]
亲自测试了一下这样可以

**Comment by luo-xiaodong** [comment]
./chain33-cli seed save -p test -s "muscle secret lamp decade crane peace rigid click virus decade patch possible vital current frozen"  可以了。感谢。文档还是要优化下，对于初学会有误导。谢谢

**Comment by vipwzw** [comment]
后面我们改进一下体验。

**Comment by vipwzw** [comment]
有问题直接在这里提问，我们看到就会回复

**Comment by andyYuanFZM** [comment]
嗯，命令脚本都是在ubuntu上编写的。  后面在Centos也验证下。

**Comment by 33cn** [comment]
很多命令都可以直接返回文本内容，方便 pipeline 处理，可以修改部分命令返回的内容。不要用json返回，因为我们还要考虑windows 的用户。

**Comment by luo-xiaodong** [comment]
谢谢
