### ISSUE TITLE
ticket close无法有效关闭

### ISSUE THREAD

**Issue by liukyo** [33cn/chain33#1015]
使用比特元钱包（Windows版)挖矿功能，挖矿一段时间后，根据官方手册进行关闭挖矿，无法有效关闭挖矿，出现如下现象：
1. ticket close执行后，仍然有1张票未关闭（如果票数大于1张的话）
2. ticket clsoe执行后，提示“no ticket to be close”,  执行ticket count显示ticket还存在
![8bfe85c84c06cdb5f5d416339ef3d4c](https://user-images.githubusercontent.com/25178699/112123445-3c9eed80-8bfc-11eb-97b1-c6530346d8c5.png)

**Comment by mdj33** [comment]
closed in plugin 
ticket close 优化 #979
