### ISSUE TITLE
新增随机数Hash插件

### ISSUE THREAD

**Issue by jixingwei** [33cn/chain33#103]
1. 建立一个随机数插件，各执行器可以通过封装好的消息，像获取区块高度那样，简单的从随机数插件获取一个Hash值

2. 随机数插件，能够支持多种算法，根据配置文件选择具体的，与共识相关的算法，第一期支持ticket数据

**Comment by jixingwei** [comment]
方案说明：
1. 在chain33/system/里增加randnum模块，由base实现基本的消息处理，这里randnum只处理一种消息，请求随机数HASH消息，分发给child处理
2. 在plugin/里增加randnum模块，ticket/dpos等作为randnum的child，以ticket为例，实现从区块中获取ticket交易，并根据规则生成一个Hash返回给请求者，兼容主链和平行链的请求，对于主链，直接根据请求者提供的高度来获取区块计算，对于平行链，根据请求者提供的交易HASH，获取主链对应高度，再进行计算

**Comment by vipwzw** [comment]
我觉得没有必要这样处理，dapp/ticket 模块中增加一个接口:  GetRandHash 就可以了。

**Comment by jixingwei** [comment]
就是其他的dapp，直接到ticket这里来请求吗

**Comment by vipwzw** [comment]
先简单一点处理把。后面其他的比如tendermint 也要加，也可以在他的dapp query 里面增加一个相同的接口。而用户配置一下 执行器的名称就可以了。

**Comment by vipwzw** [comment]
统一 通过 Query 接口处理。

**Comment by vipwzw** [comment]
client.Query

**Comment by vipwzw** [comment]
用client 包。

**Comment by jixingwei** [comment]
这个Query实际由谁来相应呢

**Comment by vipwzw** [comment]
Query 已经有了。。

**Comment by vipwzw** [comment]
![image](https://user-images.githubusercontent.com/1617585/49002217-f5be9b80-f199-11e8-93c5-2c7ff466349c.png)

**Comment by vipwzw** [comment]
通过这个接口，可以在同一条链中调用，如果是平行链，那么用rpc 接口来调用

**Comment by vipwzw** [comment]
rpc接口调用主链

**Comment by jixingwei** [comment]
通过Query接口，发消息给ticket执行器，让ticket来进行实际逻辑计算，然后返回给调用者？

**Comment by vipwzw** [comment]
是的，这样可以吗？

**Comment by jixingwei** [comment]
我想一下，应该可以实现

**Comment by vipwzw** [comment]
平行链的调用主链随机数，可能只能用rpc 接口来做。这个可靠行上会差一些，后面我们再来研究进一步的方案。先实现一个简单的版本

**Comment by jixingwei** [comment]
@vipwzw 直接放到ticket的Query接口，在调试的时候遇到一个问题。由于需要获取最近几个区块信息，在尝试调用ticket.GetApi().GetBlocks(req)时发现，对于Query接口，driverbase没有设置过env，这个api是空的。

**Comment by vipwzw** [comment]
@jixingwei  先修复 driverbase env 的问题。设置一下 API
