### ISSUE TITLE
chain33启动需支持主机域名方式启动，便于支持在k8s中部署

### ISSUE THREAD

**Issue by harrylee2015** [33cn/chain33#1039]
在k8s中一个chain33联盟链由多个pod chain33节点组成，而k8s拉起的pod是没法指定ip,拉起的pod ip都是随机分配的,而且当拉起的pod因为某些原因挂掉之后，会重新拉起一个pod，新起的pod ip也会发生改变，因次用k8s部署联盟不太方面，可能需要引入其他应用组件曲线解决目前遇到的问题，如果chain33能够直接支持主机域名方式启动的话，可能更方便chain33在k8s中部署

**Comment by vipwzw** [comment]
能详细描述一下吗？
