### ISSUE TITLE
命令行关闭节点 p2p panic

### ISSUE THREAD

**Issue by bysomeone** [33cn/chain33#1047]
cli close 关闭节点，p2p panic

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xf49d10]

goroutine 305 [running]:
github.com/33cn/chain33/system/p2p/dht/protocol/peer.(*Protocol).refreshSelf(0xc003400700)
        /home/jiangpeng/go/src/github.com/33cn/chain33/system/p2p/dht/protocol/peer/peerinfo.go:60 +0x30
github.com/33cn/chain33/system/p2p/dht/protocol/peer.InitProtocol.func1(0xc003400700)
        /home/jiangpeng/go/src/github.com/33cn/chain33/system/p2p/dht/protocol/peer/peer.go:101 +0x170
created by github.com/33cn/chain33/system/p2p/dht/protocol/peer.InitProtocol
        /home/jiangpeng/go/src/github.com/33cn/chain33/system/p2p/dht/protocol/peer/peer.go:88 +0x607

peer info相关代码 @libangzhu

**Comment by libangzhu** [comment]
收到

**Comment by bysomeone** [comment]
chain33 master分支

**Comment by yann-sjtu** [comment]
> cli close 关闭节点，p2p panic
> 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xf49d10]
> 
> goroutine 305 [running]:
> github.com/33cn/chain33/system/p2p/dht/protocol/peer.(*Protocol).refreshSelf(0xc003400700)
> /home/jiangpeng/go/src/github.com/33cn/chain33/system/p2p/dht/protocol/peer/peerinfo.go:60 +0x30
> github.com/33cn/chain33/system/p2p/dht/protocol/peer.InitProtocol.func1(0xc003400700)
> /home/jiangpeng/go/src/github.com/33cn/chain33/system/p2p/dht/protocol/peer/peer.go:101 +0x170
> created by github.com/33cn/chain33/system/p2p/dht/protocol/peer.InitProtocol
> /home/jiangpeng/go/src/github.com/33cn/chain33/system/p2p/dht/protocol/peer/peer.go:88 +0x607
> 
> peer info相关代码 @libangzhu

这个好像修复了，跑的不是最新的代码？

**Comment by bysomeone** [comment]
> EROR[05-11|16:46:32] handle stream module=p2p.protocol panic error="runtime error: invalid memory address or nil pointer dereference"
> github.com/33cn/chain33/system/p2p/dht/protocol/peer.(*Protocol).handleStreamPeerInfoOld(0xc003c61500, 0x1a8f700, 0xc0038cd740)
> /home/jiangpeng/go/src/github.com/33cn/chain33/system/p2p/dht/protocol/peer/handler.go:68 +0x14e
> github.com/33cn/chain33/system/p2p/dht/protocol.HandlerWithClose.func1(0x1a8f700, 0xc0038cd740)
> /home/jiangpeng/go/src/github.com/33cn/chain33/system/p2p/dht/protocol/wrapper.go:166 +0x81
> github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1(0xc002dd8400, 0x1a, 0x7f1f81dc9100, 0xc0038cd740, 0x1, 0x0)
> /home/jiangpeng/go/pkg/mod/github.com/libp2p/go-libp2p@v0.10.3/p2p/host/basic/basic_host.go:566 +0x9d
> created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
> /home/jiangpeng/go/pkg/mod/github.com/libp2p/go-libp2p@v0.10.3/p2p/host/basic/basic_host.go:416 +0x63c

refresh panic没有了，peerinfo这个还存在 @yann-sjtu
