### ISSUE TITLE
p2pstore 单元测试panic

### ISSUE THREAD

**Issue by bysomeone** [33cn/chain33#1060]
--- FAIL: TestInit (1.22s)
panic: interface conversion: interface {} is *types.Reply, not *types.BlockBodys [recovered]
	panic: interface conversion: interface {} is *types.Reply, not *types.BlockBodys

goroutine 24 [running]:
testing.tRunner.func1(0xc0000f4500)
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:874 +0x69f
panic(0x1560fe0, 0xc0046a2450)
	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2
github.com/33cn/chain33/system/p2p/dht/protocol/p2pstore.TestInit(0xc0000f4500)
	/home/runner/work/chain33/chain33/system/p2p/dht/protocol/p2pstore/p2pstore_test.go:54 +0x2494
testing.tRunner(0xc0000f4500, 0x184d4d0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:960 +0x652
FAIL	github.com/33cn/chain33/system/p2p/dht/protocol/p2pstore	1.249s
ok  	github.com/33cn/chain33/system/p2p/dht/protocol/peer	5.377s

@yann-sjtu

**Comment by yann-sjtu** [comment]
好的
