### ISSUE TITLE
p2p ut fail

### ISSUE THREAD

**Issue by bysomeone** [33cn/chain33#1078]
--- FAIL: Test_p2p (4.40s)
    p2p_test.go:489: listpeer []
    p2p_test.go:492: discovery update <nil>
    p2p_test.go:494: findlocalPeers [{: []}]
    p2p_test.go:280: h1 Qmdr9sAFALy7Rtt9c2hDeoziCfmsQQVriN4vEEZjrQ7gEd
    p2p_test.go:289: h2 QmaqSBkFeo5kbMkPWkkFSwiBKtHXt8XvKMsAMbPq5wnXoz
    p2p_test.go:298: h3 QmeCWyeYLQEpTQwC3NaZQbffBwCSoArrPwT3MpLpraseR9
    p2p_test.go:334: 
        	Error Trace:	p2p_test.go:334
        	            				p2p_test.go:498
        	Error:      	Received unexpected error:
        	            	failed to dial QmaqSBkFeo5kbMkPWkkFSwiBKtHXt8XvKMsAMbPq5wnXoz:
        	            	  * [/ip4/127.0.0.1/tcp/22346] dial backoff
        	Test:       	Test_p2p
    p2p_test.go:473: removed path /tmp/chain33datadir-582169296

**Comment by libangzhu** [comment]
大概率是测试端口被其他应用重复绑定了
