### ISSUE TITLE
p2p ut fail

### ISSUE THREAD

**Issue by bysomeone** [33cn/chain33#1088]
--- FAIL: TestPrivateNetwork (1.26s)
    p2p_test.go:210: same privatenetwork test success
    p2p_test.go:226: 
        	Error Trace:	p2p_test.go:226
        	Error:      	Expected value not to be nil.
        	Test:       	TestPrivateNetwork
    p2p_test.go:228: different privatenetwork test success
    p2p_test.go:251: disable privatenetwork test success

https://github.com/33cn/chain33/pull/1087/checks?check_run_id=3320277661

**Comment by libangzhu** [comment]
这个是因为host没有关闭对节点的网络连接导致的，添加一句：
h1.Network().ClosePeer(h2.ID()) 就搞定了
