### ISSUE TITLE
目前github上面的mavl裁剪中没有加入上次说的多级裁剪机制

### ISSUE THREAD

**Issue by lyh169** [33cn/chain33#109]
目前github上面的mavl裁剪中没有加入上次说的类似于多级裁剪机制，在gitlab上面的有，我是不是将gitlab上面的同步到github上先。	
//二级裁剪高度，达到此高度未裁剪则放入该处
secondLevelPruningHeight = 1000000
//三级裁剪高度，达到此高度还没有裁剪，则不进行裁剪
threeLevelPruningHeight = 1500000
onceScanCount            = 100000
@vipwzw

**Comment by vipwzw** [comment]
你重新添加一下。

**Comment by lyh169** [comment]
好的
