### ISSUE TITLE
protobuf 1.4.3升级问题汇总

### ISSUE THREAD

**Issue by bysomeone** [33cn/chain33#1095]
## 问题汇总

protobuf 1.4.*内部实现已经不同于1.3.*,官方并不保证完全兼容, 以下是已发现问题汇总

#### 禁止值拷贝

protobuf message结构体中包含mutex字段, 禁止结构体值拷贝, 代码无能直接使用值赋值, 以及函数传参或返回需要使用指针形式, 否则go vet会检测报错

#### 编码确定性

新版默认proto.Marshal接口编码顺序是不确定的, 已经统一调整types.Encode接口, 手动设置相关参数,保证编码确定性, 但仍然可能导致历史兼容问题

```go
func Encode(data proto.Message) []byte {
	buf := &proto.Buffer{}
	// 设置确定性编码
	buf.SetDeterministic(true)
	err := buf.Marshal(data)
	if err != nil {
		panic(err)
	}
	return buf.Bytes()
}

```

#### 默认值编码

对于一个空的protobuf结构体, 即所有字段都是默认值, 如interger为0, bool为false等,  protobuf编码后的值为nil,  依赖编码后nil判定的代码, 可能会导致错乱

```go
req := &types.ReqAccountList{}
buf := types.Encode(req)
require.Nil(t, buf)

```

**Comment by 33cn** [comment]
还要处理一下性能问题

**Comment by bysomeone** [comment]
需要等 #1101 兼容问题优先处理后， 才能升级 protobuf 1.4.3

**Comment by bysomeone** [comment]
#1104 合并后需要发布一个版本, 后续基于新版本再进行protobuf 1.4.3全面升级, 保证两个版本间兼容性
