### ISSUE TITLE
你们的33.cn服务器存在巨大的漏洞！

### ISSUE THREAD

**Issue by secpoolg** [33cn/chain33#1108]
目前已经可以直接进入服务器,并获取大量数据以及文件，请联系我及时修复漏洞 Telegram:@FishMen97

<img width="865" alt="123" src="https://user-images.githubusercontent.com/89971575/131816157-e09b5d86-5e53-47aa-bec8-b0b9487cfa7b.png">

**Comment by secpoolg** [comment]
可以提示一泄露项目有 zhaob* 、BAAS、通讯。。等

**Comment by secpoolg** [comment]
<img width="408" alt="image" src="https://user-images.githubusercontent.com/89971575/131860273-4f41a89a-3876-4543-b1c2-139b4a07894f.png">
<img width="451" alt="image" src="https://user-images.githubusercontent.com/89971575/131860393-2e0422af-77ba-41b3-8e49-678c45c04f13.png">
<img width="672" alt="image" src="https://user-images.githubusercontent.com/89971575/131860513-73831b37-8f09-4a35-b805-e02fbab3ee0b.png">

**Comment by secpoolg** [comment]
Please contact me, otherwise more data will appear～

**Comment by 33cn** [comment]
和chain33 无关
