### ISSUE TITLE
使用common/db/table 遍历数据存在问题

### ISSUE THREAD

**Issue by linj-disanbo** [33cn/chain33#1211]
### 问题现象

使用tag: https://github.com/33cn/chain33/tree/v1.66.3
开启execLocalSameTime, 使用common/db/table 遍历数据, 在取第三页数据时, 取到的是第一页的数据

### 已经排除可能

1.  猜测数据量正好是完整的两页, 取第三页数据时, 可能存证问题. 调整一页的数据数量 (变小),  依然在取第三页时, 取到的是第一页的数据
2. 通过日志, 原来Seek时, key不对的问题不存在.

**Comment by Trouble-CXB** [comment]
WARN[01-17|22:14:11] cycle12                                  module=exchange.executor Primary=coins.bty:USDT:1:0000000000110000
EROR[01-17|22:14:11] table.query.ListIndex                    indexName=price prefix=coins.bty:USDT:1 primaryKey=coins.bty:USDT:1:0000000000110000 count=10 dir=0
EROR[01-17|22:14:11] ListIndex                                indexPrefix=88 p=LODB-exchange-depth-d-coins.bty:USDT:1 k=LODB-exchange-depth-d-coins.bty:USDT:1:0000000000110000 count=10 d=0
EROR[01-17|22:14:11] mergedIterator Seek                      x=0
EROR[01-17|22:14:11] goLevelDBIt Seek1                        key=LODB-exchange-depth-d-coins.bty:USDT:1:0000000000110000 find?=true
EROR[01-17|22:14:11] goLevelDBIt Seek2                        key=LODB-exchange-depth-d-coins.bty:USDT:1:0000000000110000 find?=true dbkey=LODB-exchange-depth-d-coins.bty:USDT:1:0000000011710000
EROR[01-17|22:14:11] goLevelDBIt Seek3                        key=LODB-exchange-depth-d-coins.bty:USDT:1:0000000000110000 find?=true dbkey=LODB-exchange-depth-d-coins.bty:USDT:1:0000000011710000 reverse=prev
EROR[01-17|22:14:11] mergedIterator Seek                      x=0 find=nil
EROR[01-17|22:14:11] mergedIterator Seek                      x=1
EROR[01-17|22:14:11] goLevelDBIt Seek1                        key=LODB-exchange-depth-d-coins.bty:USDT:1:0000000000110000 find?=true
EROR[01-17|22:14:11] goLevelDBIt Seek2                        key=LODB-exchange-depth-d-coins.bty:USDT:1:0000000000110000 find?=true dbkey=LODB-exchange-depth-d-coins.bty:USDT:1:0000000000110000
EROR[01-17|22:14:11] goLevelDBIt Seek4                        key=LODB-exchange-depth-d-coins.bty:USDT:1:0000000000110000 find?=true dbkey=LODB-exchange-depth-d-coins.bty:USDT:1:0000000000110000
EROR[01-17|22:14:11] mergedIterator Seek                      x=1 find=LODB-exchange-depth-d-coins.bty:USDT:1:0000000000110000
EROR[01-17|22:14:11] goLevelDBIt Seek1                        key=LODB-exchange-depth-d-coins.bty:USDT:1:0000000000110000 find?=true
EROR[01-17|22:14:11] goLevelDBIt Seek2                        key=LODB-exchange-depth-d-coins.bty:USDT:1:0000000000110000 find?=true dbkey=LODB-exchange-depth-d-coins.bty:USDT:1:0000000011710000
EROR[01-17|22:14:11] goLevelDBIt Seek3                        key=LODB-exchange-depth-d-coins.bty:USDT:1:0000000000110000 find?=true dbkey=LODB-exchange-depth-d-coins.bty:USDT:1:0000000011710000 reverse=prev
WARN[01-17|22:14:11] cycle13                                  module=exchange.executor Primary=coins.bty:USDT:1:0000000012410000
WARN[01-17|22:14:11] cycle13                                  module=exchange.executor Primary=coins.bty:USDT:1:0000000012160000
WARN[01-17|22:14:11] cycle13                                  module=exchange.executor Primary=coins.bty:USDT:1:0000000011860000
WARN[01-17|22:14:11] cycle13                                  module=exchange.executor Primary=coins.bty:USDT:1:0000000011810000
WARN[01-17|22:14:11] cycle13                                  module=exchange.executor Primary=coins.bty:USDT:1:0000000011800000
WARN[01-17|22:14:11] cycle13                                  module=exchange.executor Primary=coins.bty:USDT:1:0000000011770000
WARN[01-17|22:14:11] cycle13                                  module=exchange.executor Primary=coins.bty:USDT:1:0000000011760000
WARN[01-17|22:14:11] cycle13                                  module=exchange.executor Primary=coins.bty:USDT:1:0000000011730000
WARN[01-17|22:14:11] cycle13                                  module=exchange.executor Primary=coins.bty:USDT:1:0000000011720000
WARN[01-17|22:14:11] cycle13                                  module=exchange.executor Primary=coins.bty:USDT:1:0000000011710000
