### ISSUE TITLE
平行链重新搭建之后发现交易失败，请问是什么原因？

### ISSUE THREAD

**Issue by nancyxu1982** [33cn/chain33#1219]
步骤如下：
1.  下载平行链代码
2. 修改配置行链配置文件
3. 启动平行链，等待数据同步成功
4. 使用postman导入平行链seed
5. 使用postman导入创世地址的私钥
6. 调用Chain33.WalletTxList接口成功
curl --location -g --request POST '{{chain_url}}:8901' \
--data-raw '    {
        "jsonrpc":"2.0",
        "id":0,
        "method":"Chain33.WalletTxList",
        "params":[{"fromTx":"","count":10,"direction":0}]
    }'

7. 发送交易
   CreateRawTransaction调用没有问题
    curl --location -g --request POST '{{chain_url}}:8901' \
    --header 'Content-Type: text/plain' \
    --data-raw '{
        "jsonrpc":"2.0",
        "id":1,
        "method":"Chain33.CreateRawTransaction",
        "params":[
            {
                "to":"1AJccUkd......qAAzKQ",
                "amount":10000000,
                "fee":0,
                "note":"first test",
                "isToken":false,
                "execer":"coins" 
            }
        ]
    }'
   Chain33.CreateNoBalanceTransaction调用提示错误， **返回错误：ErrAddrNotExist**
   curl --location -g --request POST '{{chain_url}}:8901' \
--header 'Content-Type: text/plain' \
--data-raw '{
  "jsonrpc":"2.0",
  "id":1,
  "method":"Chain33.CreateNoBalanceTransaction",
  "params":[
    {
        "txHex":"0x0a05636f696e73123918010a351080ade2041a0a66697273742074657374222231414a6363556b64745a3871694b7874454c4b356d72664c7851436f7141417a4b5120......e3a22314761485970576d71414a7371527772706f4e6342385676674b7453776a63487174",
        "payAddr":"1FdiWH5VDA564eU......yM4GDaZqKS2P",
        "expire":"30s"
    }
  ]
}'

还有一个问题：我们有一个钱包项目，这个这个钱包项目的节点过期了，没有续费，所以现在只能在一台新的服务器上搭建的节点，这个节点搭建完成之后，导入seed, 导入创世地址，这个钱包项目里面所有的地址是不是就可以正常转帐了？

**Comment by nancyxu1982** [comment]
我们有一个钱包项目，这个这个钱包项目的节点过期了，没有续费，所以现在只能在一台新的服务器上搭建的节点，这个节点搭建完成之后，导入seed, 导入创世地址，是不是之前在那个过期没有续费的节点上创建的地址，在这个新创建的平行链节点里面是不是都会有？

**Comment by libangzhu** [comment]
./cli. account list 看下有没有你说的这个地址：
"payAddr":"1FdiWH5VDA564eU......yM4GDaZqKS2P",

**Comment by libangzhu** [comment]
另外平行链项目不在这里，你应该去 
33cn/plugin

**Comment by libangzhu** [comment]
调用提示错误， 返回错误：ErrAddrNotExist 说明你连接的这个节点的钱包里并没有这个地址，你先确认下这个地址是从哪里来的


"payAddr":"1FdiWH5VDA564eU......yM4GDaZqKS2P",
并不是你导入seed之后，地址就会自动创建好，请先确定这个地址的来源，如果你有此地址的私钥，那就直接倒入该地址的私钥

**Comment by nancyxu1982** [comment]
已经在在：https://github.com/33cn/plugin/issues/1143 这个下面创建新的issues，请相关人员处理一下
