### ISSUE TITLE
eth 兼容交易哈希与chain33 哈希映射

### ISSUE THREAD

**Issue by libangzhu** [33cn/chain33#1279]
**发送一笔ETH签名的交易，通过eth交易哈希 目前无法在chain33 中查询到任何交易详情，提示交易不存在**

**希望对此作出改进，能同时在chain33 rpc 与eth rpc 接口中根据接口返回的哈希或者对eth 签名交易的sha3 哈希 都可以查询到具体的交易信息**

**Comment by bysomeone** [comment]
已处理
