### ISSUE TITLE
新增feature，关键修改列表

### ISSUE THREAD

**Issue by jixingwei** [33cn/chain33#143]
项目有一些新增feature和修改，一旦这些issue关闭，之前未关注的人便不感知。不可能每个人去翻git记录。有的新功能大家不会使用，还需要咨询相关开发人员。

**Comment by 33cn** [comment]
是change log 吗

**Comment by jixingwei** [comment]
对，是这个意思，最好有简要的说明

**Comment by vipwzw** [comment]
首页有一个 CHANGLOG.md
