### ISSUE TITLE
钱包密码明文传输

### ISSUE THREAD

**Issue by thereksfour** [33cn/chain33#144]
**Describe the bug**
我抓到一些流量，显示在解锁钱包时，密码使用明文传输，这里是不是应该用公私钥加密一下，或者使用MD5。
**To Reproduce**
```
./chain33-cli wallet unlock -p test
```
抓取流量显示密码为明文

```
{
	"method": "Chain33.UnLock",
	"params": [
		{
			"passwd": "test"
		}
	],
	"id": 0
}
```
**Expected behavior**
应该用公私钥加密一下，或者使用MD5。
**Screenshots**
![image](https://user-images.githubusercontent.com/44456059/49278359-7b568a00-f4bf-11e8-930f-2cbbc033ab78.png)

**Comment by 33cn** [comment]
@icehawk-hyb   考虑rpc 模块加上ssl的支持。

**Comment by vipwzw** [comment]
配置文件中加一个 tls 选项，如果这个选项打开，那么就支持 ssl

**Comment by vipwzw** [comment]
@helpylee  改为你来处理
