### ISSUE TITLE
I found that the password stored in the log which is plain text.

### ISSUE THREAD

**Issue by thereksfour** [33cn/chain33#145]
**Describe the bug**
When I review the code, I found that the code like follow will dump the password in plain text.

```
func (store *Store) VerifyPasswordHash(password string) bool {
	var WalletPwHash types.WalletPwHash
	pwhashbytes, err := store.Get(CalcPasswordHash())
	if pwhashbytes == nil || err != nil {
		return false
	}
	err = json.Unmarshal(pwhashbytes, &WalletPwHash)
	if err != nil {
		storelog.Error("VerifyPasswordHash unmarshal", "err", err)
		return false
	}
	pwhashstr := fmt.Sprintf("%s:%s", password, WalletPwHash.Randstr) // dump the password
	pwhash := sha256.Sum256([]byte(pwhashstr))
	Pwhash := pwhash[:]
	//通过新的密码计算pwhash最对比
	return bytes.Equal(WalletPwHash.GetPwHash(), Pwhash)
}
```

**Expected behavior**
This bug appeared in Twitter before. 
https://techcrunch.com/2018/05/03/twitter-password-bug/
**Screenshots**
![image](https://user-images.githubusercontent.com/44456059/49349481-b76b3400-f6e5-11e8-9b44-4d5b453de74b.png)

**Comment by vipwzw** [comment]
@icehawk-hyb  赶紧修复一下。

**Comment by vipwzw** [comment]
@thereksfour  3q

**Comment by vipwzw** [comment]
这些bug的修复我们都会记下，等我们奖励政策出来，希望你来领取我们的奖励。

**Comment by icehawk-hyb** [comment]
@thereksfour  钱包的密码我们在数据库中存储的值是经过hash之后的值。密码不是明文存储在数据库的。这个log的打印我们会做一些过滤，将敏感接口的打印输出的过滤掉不打印出来。比如密码私钥等

**Comment by thereksfour** [comment]
@vipwzw  谢谢！
