### ISSUE TITLE
db 和 receipt 操作需求调研

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#154]
**背景**

目前 写执行器的时候，需要手工构造交易，这个引起代码非常底层和冗长。

**解决方案调研**

```
1. eos table 的概念
2. 现有系统主要的代码冗余点
3. 提供什么样的封装比较合适
4. 现有行业中主要的解决方案有什么
```

**Comment by zhengjunhe** [comment]
提供什么样的封装比较合适？是指封装交易还是对DB操作的API封装

**Comment by zhengjunhe** [comment]
@lyh169 你现在看eos的multi_index的实现的时候，可以带着这些问题看具体的实现

**Comment by lyh169** [comment]
> @lyh169 你现在看eos的multi_index的实现的时候，可以带着这些问题看具体的实现

好的
