### ISSUE TITLE
merkle tree 计算存在哈希碰撞

### ISSUE THREAD

**Issue by thereksfour** [33cn/chain33#156]
**Describe the bug**
当我阅读关于merkle tree 生成的相关代码时，经过调试，我发现在交易数为单数时，会将最后一份交易copy 一份来计算 merkle tree 的 merkleRoot，如果恶意节点接收到 [tx1,tx2,tx3] 的 block，并将  [tx1,tx2,tx3,tx3] 的交易广播出去，两者的 merkleRoot 相同，可能造成造成双花攻击。
**To Reproduce**
在 merkle.go 的 Computation 函数中，这段代码，交易数为单数时会将最后一个交易copy 一份来计算 hash
```
	for count != (1 << level) {
		if (flage&2) != 0 && matchh {
			branch = append(branch, h)
		}
		h = GetHashFromTwoHash(h, h) // Use two identical transactions to calculate the hash
		count += (1 << level)
		level++
```

**Expected behavior**

单数交易取本身哈希在merkle tree上一层计算哈希值

**Comment by thereksfour** [comment]
sorry, test this [tx1,xt2,tx3,tx4,tx5,tx6] and [tx1,xt2,tx3,tx4,tx5,tx6,tx5,tx6] , thanks!

**Comment by 33cn** [comment]
看一下我的这个测试，有相同的交易的区块是无法广播

**Comment by 33cn** [comment]
![image](https://user-images.githubusercontent.com/27620745/49498635-ac133680-f8a6-11e8-8635-bb927d284898.png)

@thereksfour 你加一下这个客服微信，给客服留言：加CTO微信。
我们老板看到了你提的这些bug，说要奖励你。

**Comment by thereksfour** [comment]
谢谢！！！
