### ISSUE TITLE
本地solo测试时，余额被自动买成ticket

### ISSUE THREAD

**Issue by litian33** [33cn/chain33#164]
**Describe the bug**
本地solo测试时，余额被自动买成ticket

**To Reproduce**
1. 配置本地solo测试环境；
2. 启动一个全新的环境；
3. 将创世地址导入钱包，这时查看余额是正确的；
4. 等候10分钟左右；
5. 再次查看此地址余额，发现coins下面仅剩余一点，其余全部被买成ticket；

**Expected behavior**
非ticket共识下，不应该启用ticket挖矿逻辑；

**Screenshots**
无

**Desktop (please complete the following information):**
 - OS: Linux  4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 - Version Chain33主干最新版本

**Comment by vipwzw** [comment]
修复可能要在 33cn/plugin#115

**Comment by litian33** [comment]
33cn/plugin#

> 修复可能要在 [33cn/plugin#115](https://github.com/33cn/plugin/issues/115)

已修复
