### ISSUE TITLE
设置交易费用后执行 SendToAddress，发生区块污染

### ISSUE THREAD

**Issue by thereksfour** [33cn/chain33#165]
**Describe the bug**
我在阅读源码中的 api 时，注意到 set_fee 可以用来设置交易费用，于是我准备测试是否会有相关的溢出，结果在我设置费用为一个大数之后，再调用 SendToAddress 时，竟然执行了一百多次 procExecAddBlock 函数，并且区块高度增加了一百多（之后每次增加的不一样，但是都很多），其中都是无效交易。
*To Reproduce**
首先设置交易费用
```
./chain33-cli wallet set_fee -a 92233720368
```
然后执行下面脚本调用 SendToAddress
```
    sendTrans = "{\"method\": \"Chain33.SendToAddress\",\"params\": [{\"From\": \"1CbEVT9RnM5oZhWMj4fxUrJX94VtRotzvs\",\"To\": \"1GhMZ7vpEEGLUmxcf8KRNedjpKZYFus9dJ\",\"amount\": 100000000}],\"id\": 0}"
    print sendTrans
    req2 = requests.post("http://localhost:8801",data=sendTrans)
```

**Expected behavior**
仅增加一个区块高度
**Screenshots**
![image](https://user-images.githubusercontent.com/44456059/49570006-78044800-f970-11e8-9675-e639a0ac0501.png)

**Comment by thereksfour** [comment]
并且当我连续向区块发送该消息时，正常交易将无法被处理

```
while True:
    sendTrans = "{\"method\": \"Chain33.SendToAddress\",\"params\": [{\"From\": \"1CbEVT9RnM5oZhWMj4fxUrJX94VtRotzvs\",\"To\": \"1GhMZ7vpEEGLUmxcf8KRNedjpKZYFus9dJ\",\"amount\": 100000000}],\"id\": 0}"
    print sendTrans
    req2 = requests.post("http://localhost:8801",data=sendTrans)
    print 'sendTrans',req2.text
```

![image](https://user-images.githubusercontent.com/44456059/49623615-5d31e200-fa09-11e8-87cb-cb2523f6871f.png)
![image](https://user-images.githubusercontent.com/44456059/49623624-67ec7700-fa09-11e8-9935-a181b92a6f4e.png)

**Comment by 33cn** [comment]
应该有三个问题: 

1. mempool 没有不应该让这样的交易进入打包环节

2. 公司模块执行删除的交易，对应的mempool 中也要删除。

3. solo 挖矿 在交易删除光了之后，应该重新挖，而不是创建出区块。

**Comment by 33cn** [comment]
@icehawk-hyb  你来修复这三个问题
