### ISSUE TITLE
平行链需要包装到主链的连接通道

### ISSUE THREAD

**Issue by litian33** [33cn/chain33#170]
目前开发平行链合约时，每个合约都需要自己创建rpc连接，去操作主链相关信息；

建议将此能力进行封装，提供统一的主链访问通道和API，降低平行链合约的开发难度和工作量；

@jixingwei  @vipwzw  @andyYuanFZM

**Comment by andyYuanFZM** [comment]
@jpeng-go 看下现在共识和合约中用到rpc链接的地方，然后看看这个放哪边比较合适。

**Comment by vipwzw** [comment]
可以谈谈你们的方案

**Comment by vipwzw** [comment]
先确定一下方案，平行链访问主链，如果发生网络错误，如何处理和回滚。

**Comment by vipwzw** [comment]
以及如何方便让合约带有这样的访问能力

**Comment by jixingwei** [comment]
@litian33 @jpeng-go 目前合约里，平行链访问主链，最常见的是判断主链高度，可以封装一些api接口，在QueueProtocol里实现grpc的处理，当合约调用api接口时（合约自身还是要有判断是否平行链这一分支，或者某些合约在平行链运行时，不关心平行链高度，只关心主链高度，这时，合约甚至不需要加平行链判断分支），直接得到相应的结果。这样，对于合约已经屏蔽了grpc接口，进而，类似于取随机数这样的操作，也可以封装了。例如，合约只调用action.api.QueryRandNum()，由QueueProtocol来判断是主链还是平行链，如果是主链，再直接调用Query，如果是平行链，则调用grpc.QueryRandNum()。

**Comment by vipwzw** [comment]
也有一些情况，可能确实是获取平行链的一些信息，而不是主链

**Comment by jixingwei** [comment]
可能加一些平行链专用的接口，不太容易误解

**Comment by vipwzw** [comment]
到主链一定是通过grpc，但是问题是grpc可能会失败，这个时候，平行链上如何处理这类异常

**Comment by jixingwei** [comment]
关于这个失败的考虑，需要结合这样的场景：合约在平行链上执行，正是因为通过grpc从主链刚刚获取了区块，然后，通过grpc到主链获取信息失败，情况是比较极端的。从合约执行的角度，是不是可以考虑阻塞在这里，因为跟主链连接断了，平行链也没有继续执行下去的必要了。另外，是不是有一个grpc切换的功能在做？

**Comment by vipwzw** [comment]
#194  这里继续讨论，这个issues 先关闭。
