### ISSUE TITLE
随机数哈希需要以api方式提供服务

### ISSUE THREAD

**Issue by litian33** [33cn/chain33#171]
目前的随机数获取方式比较复杂，还需要考虑平行链分支，使用代码需要好几十行，比较不方便；

建议将随机数获取能力封装成本地API，放到DriverBase或其它什么地方，具体合约使用时，直接调用api即可。

@jixingwei  @vipwzw @andyYuanFZM

**Comment by vipwzw** [comment]
@jixingwei  你的随机数接口添加到文档里面去

**Comment by jixingwei** [comment]
好的，我先加一下文档，分析一下怎么处理更简洁

**Comment by vipwzw** [comment]
@jixingwei  文档链接有吗？ 可以更新到这里来。或者弄一个链接也可以

**Comment by 33cn** [comment]
合并到  #194
