### ISSUE TITLE
每次清空datadir后重新同步数据，都会新生成一个node award地址

### ISSUE THREAD

**Issue by litian33** [33cn/chain33#173]
如果不删除wallet节点，只删除datadir，重新同步数据，每同步一次就会生成一个node award账户，操作多次后就会有一堆node award账户；

按照正常理解，账户应该是存在钱包中，如果钱包已经有了，应该只同步区块数据，不应该再生成新的node award地址

**Comment by 33cn** [comment]
这个主要是因为p2p 模块，的node 目录下面有一个私钥，如果datadir 被删除，这个私钥也会被删除。可以考虑把这个目录默认放到 wallet 里面去。

**Comment by vipwzw** [comment]
@helpylee  你来处理
