### ISSUE TITLE
rpc 接口 构造token交易 打币失败

### ISSUE THREAD

**Issue by libangzhu** [33cn/chain33#176]
我是通过Chain33.CreateRawTransaction 这个RPC 接口构造一笔往平行链某个地址打币的交易，签名后，查询交易详情，显示 交易不成功。
下面是我构造的过程，tokenSymbol=TEST,execName=user.p.sto.token

var params = make(map[string]interface{})
	params["to"] = txinfo.GetTo()
	params["amount"] = int64((txinfo.GetAmount() + 0.0000001) * 1e8)
	params["fee"] = 1e5
	params["note"] = txinfo.GetNote()
	params["isToken"] = true
	params["tokenSymbol"] = txinfo.GetTokensymbol()
	params["execName"] = BtyCfg.TokenExecer
	parmbs, err := json.Marshal(params)
	if err != nil {
		return "", err
	}
	postdata := fmt.Sprintf(`{"jsonrpc":"2.0","id":2,"method":"Chain33.CreateRawTransaction","params":[%v]}`, string(parmbs))

**Comment by libangzhu** [comment]
错误详情如下：
"receipt": {
                    "ty": 1,
                    "tyName": "ExecPack",
                    "logs": [
                        {
                            "ty": 1,
                            "tyName": "LogErr",
                            "log": "ErrToAddrNotSameToExecAddr",
                            "rawLog": "0x457272546f416464724e6f7453616d65546f4578656341646472"
                        }
                    ]
                },

**Comment by vipwzw** [comment]
调用是在平行链上调用的吗？

**Comment by libangzhu** [comment]
是在平行链上调用的构造平行链的交易，后来我们把 execName这个字段置为空，就正常了

**Comment by vipwzw** [comment]
主要原因是 ExecName 误用引起的问题：
ExecName 的作用看这段代码:
```go
func (base *ExecTypeBase) AssertCreate(c *CreateTx) (*Transaction, error) {
	if c.ExecName != "" && !IsAllowExecName([]byte(c.ExecName), []byte(c.ExecName)) {
		tlog.Error("CreateTx", "Error", ErrExecNameNotMatch)
		return nil, ErrExecNameNotMatch
	}
	if c.Amount < 0 {
		return nil, ErrAmount
	}
	if c.IsWithdraw {
		p := &AssetsWithdraw{Cointoken: c.GetTokenSymbol(), Amount: c.Amount,
			Note: c.Note, ExecName: c.ExecName, To: c.To}
		return base.child.CreateTransaction("Withdraw", p)
	}
	if c.ExecName != "" {
		v := &AssetsTransferToExec{Cointoken: c.GetTokenSymbol(), Amount: c.Amount,
			Note: c.Note, ExecName: c.ExecName, To: c.To}
		return base.child.CreateTransaction("TransferToExec", v)
	}
	v := &AssetsTransfer{Cointoken: c.GetTokenSymbol(), Amount: c.Amount, Note: c.GetNote(), To: c.To}
	return base.child.CreateTransaction("Transfer", v)
}

```

总结一下:

```
execname 其实不是执行器名称的意思
c.IsWithdraw  == true   从 c.ExecName 取回token
c.IsWithdraw  == false 发送资产到 c.ExecName
```

你原来的意思是要发送交易给某个非合约地址。
但是：
因为加上了 execname 这个字段，变成了发送交易给合约地址，这样两个地址肯定不匹配
