### ISSUE TITLE
Query the frozen and active balance in all exec address for specific address

### ISSUE THREAD

**Issue by zzh33cn** [33cn/chain33#18]
1.the key store format int the Store DB is like this `"mavl-coins-bty-exec-exec_addr-addr"`，eg：`mavl-coins-bty-exec-16htvcBNSEA7fZhAdLJphDwQRQJaHpyHTp:1JmFaA6unrCFYEWPGRi7uuXY1KthTJxJEP`，
`16htvcBNSEA7fZhAdLJphDwQRQJaHpyHTp` is the exec address，`1JmFaA6unrCFYEWPGRi7uuXY1KthTJxJEP` is the specific address.

2.we can use command as following to query the result:
`cli stat exec_balance -symbol bty -exec coins -addr 1JmFaA6unrCFYEWPGRi7uuXY1KthTJxJEP -exec_addr 16htvcBNSEA7fZhAdLJphDwQRQJaHpyHTp -height -1`
the result is like this:
```
{
    "totalAmount":10,
    "frozenAmount":3,
    "activeAmount":7,
    "execBalances":[
        {
            "execAddr":"xxxx",
            "frozen":1,
            "active":2
        },
        ...
    ]
} 
```

**Comment by 33cn** [comment]
数据库底层提供一个 List 接口, 让上层用户可以自定义查询需求。

**Comment by chain33-admin** [comment]
目前大部分用户是中文用户，可以用中文来写，可以在中文后面付上英文。

**Comment by 33cn** [comment]
OK

**Comment by 33cn** [comment]
稍微格式化一下，用md

**Comment by zzh33cn** [comment]
修改涉及的文件列表：

> github.com\33cn\chain33\account\account.go
> github.com\33cn\chain33\account\account_test.go
> github.com\33cn\chain33\client\mocks\api.go
> github.com\33cn\chain33\client\queueprotocol.go
> github.com\33cn\chain33\client\queueprotocolapi.go
> github.com\33cn\chain33\common\db\mvcc_iter_test.go
> github.com\33cn\chain33\rpc\client.go
> github.com\33cn\chain33\rpc\jrpchandler.go
> github.com\33cn\chain33\system\dapp\commands\types\types.go
> github.com\33cn\chain33\system\dapp\commands\stat.go
> github.com\33cn\chain33\system\store\mavl\mavl_test.go
> github.com\33cn\chain33\system\store\base.go
> github.com\33cn\chain33\types\proto\db.proto
> github.com\33cn\chain33\types\proto\statistic.proto
> github.com\33cn\chain33\types\account.pb.go
> github.com\33cn\chain33\types\db.pb.go
> github.com\33cn\chain33\types\event.go
> github.com\33cn\chain33\types\statistic.pb.go
> github.com\33cn\chain33\types\types.go
> github.com\33cn\chain33\types\types_test.go
> github.com\33cn\chain33\util\cli\cli.go

**Comment by vipwzw** [comment]
第一阶段已经完成，快速查找版本还没有开始

**Comment by vipwzw** [comment]
用外接数据库解决这个问题
