### ISSUE TITLE
wasm或者evm合约LocalDB存储时存在跨合约操作的风险

### ISSUE THREAD

**Issue by zhengjunhe** [33cn/chain33#183]
chain33/executor/allow.go:isAllowLocalKey中的实现中
execer = types.GetRealExecName(execer)
当调用user.wasm.xxx合约时，通过上述调用获取到的execer为wasm，
这样就会存在用户自定义合约跨合约操作的风险，
这样的情况也会发生在user.evm.xxx的合约执行过程中。
@vipwzw 你认为呢？

**Comment by 33cn** [comment]
是这样的，当初设计的时候两点考虑：
```
1.合约只要不影响其他执行器就可以了，给予合约最大的自由度。
2. 子合约写的范围要合约本身来控制，系统只考虑主合约。
```

**Comment by vipwzw** [comment]
localdb 的控制不会像 statedb 这样复杂了，这个权限控制交给合约本身。

**Comment by vipwzw** [comment]
增加一个权限: 允许 user.evm.xxx 可以写 user.evm.xxx 的权限
