### ISSUE TITLE
如何在平行链中创建主链的交易

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#186]
如果自己都链是平行链，那么可以创建自己平行链下面的交易。如果是主链，那么可以创建平行链，也可以创建主链的交易。但是目前有一个不支持：平行链上创建主链的交易。

解决方案

增加一个规则，如果要在平行链中创建主链交易，那么在执行器前面加上一个 # eg(#coins) ，那么重写规则变成 #coins -> coins 这样可以实现平行链可以构造主链的交易（不会重写为user.p.paraname.coins）。这个构造可能并不常见，所以用了这样的一个hack 的方式。

**Comment by andyYuanFZM** [comment]
现在主链也可以构建平行链的交易，比如在主链上构建sto链的转token交易，可以如下写（把execName写全）：
{"jsonrpc":"2.0","id":2,"method":"Chain33.CreateRawTransaction","params":[{"amount":15000000000,"execName":"user.p.sto.token","fee":100000,"isToken":true,"to":"122xqpBrbhAAgNAUiXfAwBjXEYvPXJFdD2","tokenSymbol":"TTST"}]}' 

但如果在平行链上构建相同的交易，传参的时候，execName要传空，如下：
{"jsonrpc":"2.0","id":2,"method":"Chain33.CreateRawTransaction","params":[{"amount":15000000000,"execName":"","fee":100000,"isToken":true,"to":"122xqpBrbhAAgNAUiXfAwBjXEYvPXJFdD2","tokenSymbol":"TTST"}]}'

**Comment by vipwzw** [comment]
#176  看一下这个问题，应该是 ExecName 误用引起的。
