### ISSUE TITLE
所有的RPC用testnode 的方式添加 rpc 接口的测试

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#188]
所有的RPC用testnode 的方式添加 rpc 接口的测试
目前的rpc 接口的测试方式，不能真实的测试出内在的业务逻辑。
现在每个包都基本上有一个 rpc_real_test.go 可以用这个测试文件构造一些业务逻辑，实现相对真实的测试。最近发现的一些bug，发现仅仅用mock 的方式，测试不出一些潜在的问题。

**Comment by vipwzw** [comment]
@andyYuanFZM  @zhengjunhe  你们看一下如何分工一下。这样可以保证接口能用，否则现在经常改了一个代码就影响接口和稳定性。

**Comment by vipwzw** [comment]
plugin 中也要做类似的测试。

**Comment by vipwzw** [comment]
#190  我添加了一个例子，真实的测试了 SendToExec 这个函数

**Comment by zhengjunhe** [comment]
好的 我和老袁分工合作下吧

**Comment by andyYuanFZM** [comment]
南京的同学先针对自己写的合约，以及正在写的合约的RPC调用，补充一下测试用例。 参考上面的#190那个例 子。 目前我们也遇到几次版本升级后，程序跑的跟预期结果有出入，花了很多时间去调试。  大家先针对自己的合约抽空补一下测试用例 
@harrylee2015 @Hugo-Huang @zzh33cn @litian33 @jixingwei @ jpeng-go @caopingcp

**Comment by harrylee2015** [comment]
没有新增rpc接口，复用系统原有的rpc接口，这个测试用例怎么写？直接在rpc_real_test.go 下面增加用例吗

**Comment by vipwzw** [comment]
现在改成了直接用 shell 写测试。
