### ISSUE TITLE
平行链grpc接口封装

### ISSUE THREAD

**Issue by jpeng-go** [33cn/chain33#194]
**现状**
平行链共识和大部分dapp的处理过程中都需要从主链获取关键信息，例如主链高度，随机数等，当前的实现是使用grpc客户端连接主链调用对应的rpc接口获取，每次使用都要new一个新的grpc客户端然后建立连接，这些都是重复工作量，且对后续的第三方开发者开发dapp也不友好

**期望**
对grpc客户端的操作封装，使用者只需要知道调用哪个API即可

**方案**
1.  仿照jsonRpc client，将新建gprc客户端和连接主链rpc的动作封装到一个类似NewGrpcClient的API中，使用者只需要调用NewGrpcClient就能回去grpc客户端，然后调用rpc接口

2. QueueProtocol中封装grpc client，对于平行链使用的API，在节点为平行链时，API内部自动创建grpc client，请求发送到主链grpc server，使用者只需要调用一步API即可

**利弊**
方案1 比较灵活，不改动已有的queue结构，但使用者需要先NewGrpcClient再调用api
方案2 grpc对使用者完全不可见，使用简单只需直接调用API，可能需要改动QueueProtocolOption

@vipwzw @andyYuanFZM @litian33 @jixingwei 请评估

**Comment by vipwzw** [comment]
QueueProtocol 的设计和 rpc 无关，她是对消息对封装，目前只用于模块内部对通讯。所以这是两个无关的东西，不能把两个无关的东西封装到一起。可以创建一个 util/api 的包，通过组合的方式，把常见的操作封装在一起。
```
 api.New("channel") -> 表示调用 QueueProtocolAPI
 api.New("grpc:https://localhost:8802") -> 表示调用GRPC （api.New("grpc:mainnet") 可以表示连接主网，默认去读主网的配置，api.New("grpc") 表示链接本地grpc ）
 api.New("jrpc:https://localhost:8801") -> 表示调用jsonrpc 
```

```
创建一个接口,  这个接口包括了 grpc jrpc channel  共同支持的函数
```

注意：
```
channel 一般是可靠的，但是也可能在负载非常高的情况下发生超时。
grpc 和 jrpc 可能会因为网络问题，发生请求错误。
保证区块执行的时候，只会调用到readonly的接口
```

错误处理方法：
```
调用api 发生错误的情况下，需要一个错误处理机制。
1. 可以设置一个 超时时间。这个时候，grpc 和 jrpc 和 channel 的处理不同，如果超时时间没有到，那么
grpc 和 jrpc 可以是 sleep 一会retry 而 channel 只需要等待超时就可以了。

2. 如果发生超时，比较好的做法是cancel 区块的执行，然后过一段时间后，重新发起区块执行。这个机制一定要保证，否则，万一执行过程中，网络中段，那么可能会发生执行结果和别人不同 的情况。
```

**Comment by vipwzw** [comment]
api.New("grpc:https://localhost:8802,https://domain:8802") 可以实现自动切换主链节点。

**Comment by jpeng-go** [comment]
1. jrpc的API调用者一般都是非golang的客户端，比如java，直接使用http.post来调用chain33的jrpc接口，与grpc,queuecllient统一封装成go的通用API客户端其实意义不大，并不会优化非golang客户端的调用方式
2. queueClient本身只用在内部模块通信，不对外开放，jrpc和grpc的实现其实都是调用的queuecllient，queuecllient基本每个模块都有个，且调用简单，如果把queueClient封装到统一客户端反而变复杂了
3. jrpc和grpc，queuecllient的关系：jrpc和grpc有一些同样功能的API，但二者的使用者和调用方式完全不同，而queuecllient是jrpc和grpc的底层实现，这两者本身就是不同场景下对queueclient的封装

当前的痛点主要还是grpc在平行链间的调用时代码会略显冗余，还是建议仿照jsonclient实现gclient,在gclient中封装rpc连接，自动切换主链节点等功能。 
@vipwzw 请评估
