### ISSUE TITLE
添加一个接口 rewrite transaction

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#200]

**Comment by vipwzw** [comment]
除了payload 字段，其他字段都可以被修改。

Chain33.RewriteTransaction
```
	Execer
	Fee
	Expire
	Nonce
	To
```
如果修改了 Execer 并且是平行链都情况，那么要重写To 否则交易会检查不过。

**Comment by vipwzw** [comment]
@zhengjunhe  安排人处理一下这个需求

**Comment by zhengjunhe** [comment]
@mdj33 你处理一下吧 谢谢

**Comment by mdj33** [comment]
因构造交易时候过期时间和fee都是缺省的，构造时候添加这接口对cli来说比较冗余，新增加一个可以修改交易的接口，使得fee和expire可以修改，另外，在签名时候也可以需要添加这个修改参数，方便在签名时候设置手续费
