### ISSUE TITLE
交易出现中文address

### ISSUE THREAD

**Issue by bf002967** [33cn/chain33#207]
节点：
豆子钱包 — https://beanwallet.com/api
execer — user.p.guodun.token

交易哈希：
0xea68c220f4d4cb31927009176aff7acaa1a51579b5de739bd7c49192a4ca598b
0xc93ab2c493e90f02f5bfd9e011d03e88e06998bc72f828aa61aeab83bd3301f1
0x29b58d3448144fbaefd6ffaa391a7fc2696b9972429c94c22819b903fb9ea4c1
...

异常地址：
重庆市九龙坡区龙泉路69号轻港佳宛19一12

Q：
地址校验是否正确

**Comment by vipwzw** [comment]
![image](https://user-images.githubusercontent.com/1617585/50067064-03e06480-01fa-11e9-86a5-a0635f667402.png)
感觉这个问题是一个显示问题，交易实际上已经是失败了

**Comment by vipwzw** [comment]
浏览器没有正确判断执行状态
