### ISSUE TITLE
GetTxByToken 查询token相关交易，6.0.2的节点返回ErrActionNotSupport

### ISSUE THREAD

**Issue by zoexx** [33cn/chain33#208]
**Describe the bug**
如题

http://120.79.156.149:8801 Chain33.Version 5.3.0 返回正常期望的结果

http://39.98.51.242:8901 Chain33.Version 6.0.2 返回 ErrActionNotSupport

入参：
```json
{
    "id": 1544955088350,
    "jsonrpc": "2.0",
    "method": "Chain33.Query",
    "params": [
        {
            "execer": "token",
            "funcName": "GetTxByToken",
            "payload": {
                "symbol": "ZWGYBA",
                "direction": 0,
                "height": -1,
                "flag": 0,
                "index": 0,
                "count": 8
            }
        }
    ]
}
```

**Comment by vipwzw** [comment]
![image](https://user-images.githubusercontent.com/1617585/50067035-eb704a00-01f9-11e9-825b-0cf5a5dcc609.png)
感觉这个问题是浏览器显示的问题，交易实际上执行失败了。

**Comment by linj-disanbo** [comment]
确认配置， 开启GetTxByToken 这个接口。
[exec.sub.token]
saveTokenTxList=true

**Comment by zoexx** [comment]
ps:
> false 的话是没有开启。 这个将会保存token交易相关的额外信息， 一般节点不用开始。 但只是开启只会有后续同步的交易信息， 前面已经同步的不会生成了。
