### ISSUE TITLE
目前裁剪测试中发现的分叉产生时候的问题：

### ISSUE THREAD

**Issue by lyh169** [33cn/chain33#210]
在同步区块时候，有可能将分叉的区块同步过来，而这个区块中某一笔交易正好改变了之前账户的状态，这样就会出现裁剪时候，将分叉之前正常的状态给删除掉。应对这种问题的话就是需要在执行statedb时候也需要将分叉产生的statedb的数据删除掉。这种概率的话 比较小。

**Comment by xies1031** [comment]
测试发现在最高高度下接收广播，出现这种情况的概率非常高，3台机子跑了一段时间后都出现了同样的问题后数据库损坏
