### ISSUE TITLE
同步的时候经常mempool报错

### ISSUE THREAD

**Issue by 33cn** [33cn/chain33#211]
![image](https://user-images.githubusercontent.com/27620745/50072919-d69fb080-0211-11e9-95fd-b035619da621.png)

**Comment by icehawk-hyb** [comment]
这个应该属于正常现象，在block同步阶段，blockchain模块这边是处于不同步状态，mempool这边会获取blockchain的同步状态来判断要不要处理接收到的广播tx交易。由于blockchain没有同步，所以无法获取到交易账户的最新信息，此时不能处理收到的广播交易。
