### ISSUE TITLE
bityuan5.3.0 panic

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#217]
![image](https://user-images.githubusercontent.com/1617585/50198509-f1dffc80-0386-11e9-8f85-ec733306be8f.png)
堆栈如图，要看一下最新版本是否有这个bug。

**Comment by icehawk-hyb** [comment]
最新版本存在这方面的隐患，目前的代码处理：就是启动blockchian时在InitIndexAndBestView函数中通过height获取blockheader 然后将blockheader信息加载到缓存中，如果此时从数据库获取blockheader失败，会直接退出此函数导致ChainView 和index没有被初始化。

修改方案：在InitIndexAndBestView函数中，通过height获取blockheader失败时直接panic掉。
