### ISSUE TITLE
随机数hash 获取可能会存在分叉的bug

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#231]
通过区块高度获取随机数的方式可能会因为主节点的分叉引起不同的节点取出不同的值。

1. 查询当前平行链区块，对应主链区块的hash值。(这个值是唯一的)

2. 用这个hash值获取 n 个块组合的随机数。
2.1 通过hash值，查询到block （注意，这个block 可能不是在主链上的）
2.2 通过block 查询到 prevhash ，再查询上一个block。

总结来说：高度是不靠谱的，必须用hash，并检查是一个完整的链条，这样才是唯一的。

**Comment by vipwzw** [comment]
@jixingwei

**Comment by jixingwei** [comment]
如上所述:以时时彩为例，执行一笔开奖交易时，平行链到主链上查询这笔交易对应的高度，根据这个高度，在主链上找相应的块，进行计算。首先，一定会查到这笔交易，否则执行出错(刚好在非常极端的情况下，这时主链回滚了)。而后，平行链这个高度也会被回滚。其他的情况，拉下来的几个高度，平行链各节点对应的主链，如果出现不一致的情况，那么主链分叉了，会回滚，平行链也会回滚。应该平行链本身不会出现随机数计算分叉的问题。看看这样理解是否一致呢
