### ISSUE TITLE
工具需要增加创建项目的功能

### ISSUE THREAD

**Issue by chain33-shg** [33cn/chain33#26]
工具程序tools可以考虑加入创建简单的工程创建向导功能， 内含简单的设置、查询值的合约。类似于一键创建bityuan的项目。

**Comment by vipwzw** [comment]
bityuan 项目地址 https://github.com/bityuan/bityuan

**Comment by 33cn** [comment]
这个已经完成了吗？完成了可以给 xs 测试一下
