### ISSUE TITLE
如何搭建一个属于自己的 bityuan 区块查询平台

### ISSUE THREAD

**Issue by dulumao** [33cn/chain33#266]
https://mainnet.bityuan.com/index

**Comment by dulumao** [comment]
类似这种的，主网和测试网的区块查询

**Comment by dulumao** [comment]
平台代码是不是没有开源呢

**Comment by vipwzw** [comment]
这个代码没有开源，你只要做一个前端就可以， 不需要开发新的api
所有的接口，钱包都已经提供

**Comment by vipwzw** [comment]
@dulumao  如果你们想做，我们可以提供免费技术支持，只是目前我们在跑的代码，不能直接给你。

**Comment by dulumao** [comment]
@vipwzw 好的谢谢,技术应该联系谁呢，是否有群

**Comment by vipwzw** [comment]
@dulumao  可以加我们客服微信拉技术群

**Comment by vipwzw** [comment]
https://chain.33.cn/  在网页最后面有二维码

**Comment by zoexx** [comment]
@dulumao  @vipwzw  这里有一个通用的查询平台，可以试用 http://parallel.bityuan.com/index  
点击导航栏中的设置按钮，修改节点地址即可

**Comment by dulumao** [comment]
@zoexx 好的
