### ISSUE TITLE
使用token_assets查询指定地址的token余额，只针对token和trade合约生效

### ISSUE THREAD

**Issue by xies1031** [33cn/chain33#268]
**Describe the bug**
使用token_assets查询指定地址的token余额，只针对token和trade合约生效，对其他合约如multisig合约未生效

@linj-disanbo

**Comment by linj-disanbo** [comment]
当时实现只考虑 token和trade合约。 
现在新加了 asset balance 命令， 可以通用的查询所有资产。 
应该可以废弃这个命令 @vipwzw ， 你怎么看

**Comment by vipwzw** [comment]
@linj-disanbo  在下下个版本中删除，在文档中标记为废弃。

**Comment by vipwzw** [comment]
在 6.2   版本中删除

**Comment by linj-disanbo** [comment]
> @linj-disanbo 在下下个版本中删除，在文档中标记为废弃。

这个接口有列表功能， 目前还不能被替代。

**Comment by linj-disanbo** [comment]
不能显示其他合约的问题已经解决
https://github.com/33cn/plugin/pull/13
