### ISSUE TITLE
如何处理 can not disable isRecordBlockSequence

### ISSUE THREAD

**Issue by zoexx** [33cn/chain33#275]
![image](https://user-images.githubusercontent.com/8450959/51073587-0d9ca100-16ae-11e9-8c69-156d256b7e8f.png)

这是由于 chian33.toml 意外变更 引起的错误吗？

遇到这个问题应该如何解决呢？

1 手动修改配置文件中的某一行代码？更改代码之后需要重新同步吗？
2 更换数据目录重新同步？

@icehawk-hyb

**Comment by vipwzw** [comment]
![image](https://user-images.githubusercontent.com/1617585/51085016-42702d00-176e-11e9-8719-aac631e08fa8.png)
这个配置设置为true 重新启动节点
