### ISSUE TITLE
同步时未过滤对不存在执行器的错误打印

### ISSUE THREAD

**Issue by xies1031** [33cn/chain33#281]
![image](https://user-images.githubusercontent.com/44956625/51232398-85fead00-19a1-11e9-821a-331b83ad3dad.png)
主链上不存在writer执行器，同步中平行链中使用该执行器导致大量打印错误

game合约也有对应的打印
![image](https://user-images.githubusercontent.com/44956625/51241142-26f86280-19b8-11e9-89ec-f7c60ba65a6f.png)

**Comment by vipwzw** [comment]
@icehawk-hyb  把错误注释掉
