### ISSUE TITLE
wallet模块存储地址时可否新增标识（来自导入，来自创建，空投地址）

### ISSUE THREAD

**Issue by zoexx** [33cn/chain33#285]
**Is your feature request related to a problem? Please describe.**
目前wallet模块在存储account信息时只有一个额外的Label字段，并且可修改  
在做桌面端钱包时，除了界面上的点击创建和导入之外，cli也会开放给用户  
通过cli创建/导入的地址  客户端就无法区分了  

**Describe the solution you'd like**
是否可以给Account增加一个readonly 的 Type字段，表明该地址来自：  
1. 创建的
1. 空投的（需要提示用户备份私钥）
1. 导入的（需要提示用户备份私钥）

**Describe alternatives you've considered**
目前的做法不够准确，暂时能满足不使用cli操作account的客户

相关接口文档 
- 创建账户 https://chain.33.cn/document/94#1.5%20%E5%88%9B%E5%BB%BA%E8%B4%A6%E6%88%B7%20NewAccount
- 导入私钥 https://chain.33.cn/document/94#1.8%20%E5%AF%BC%E5%85%A5%E7%A7%81%E9%92%A5%20ImportPrivKey
- 获取账户列表https://chain.33.cn/document/94#1.6%20%E8%8E%B7%E5%8F%96%E8%B4%A6%E6%88%B7%E5%88%97%E8%A1%A8%20GetAccounts

![image](https://user-images.githubusercontent.com/8450959/51258270-8e2c0c00-19e4-11e9-9b41-dd670b04df66.png)

**Comment by vipwzw** [comment]
优先级可以稍微低一点。

**Comment by vipwzw** [comment]
先客户端不精确对处理一下，分类错误，也不会影响使用。
