### ISSUE TITLE
RPC接口Chain33.SendToAddress的note参数存在bug

### ISSUE THREAD

**Issue by litterboypoi** [33cn/chain33#291]
**Describe the bug**
调用Chain33.SendToAddress接口是note字段传入“test2019118”，
接口返回错误“illegal base64 data at input byte 8”

**Expected behavior**
note字段传入普通的字符串不会返回错误

**Screenshots**
![image](https://user-images.githubusercontent.com/25950723/51363482-26c0aa00-1b13-11e9-9fc2-b49033b08c4d.png)
![image](https://user-images.githubusercontent.com/25950723/51363490-317b3f00-1b13-11e9-940b-3f1b109458e3.png)

**Comment by niniwzw** [comment]
最新的版本这个问题已经修复

**Comment by vipwzw** [comment]
更新最新的版本重新编译就可以
