### ISSUE TITLE
DoS risk on `QueryTicketInfoList`

### ISSUE THREAD

**Issue by vang1ong7ang** [33cn/chain33#311]
**Describe the bug**

The RPC interface, `Chain33.QueryTicketInfoList`, may cause the chain33 process hang.

This issue can be reproduced on:
1. https://mainnode.bityuan.com:8801
2. https://testnet.bityuan.com/api

**To Reproduce**

Execute the following commands in parallel

```bash
curl https://testnet.bityuan.com/api -d '{"jsonrpc":"2.0","id":0,"method":"Chain33.QueryTicketInfoList","params":[{}]}'
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vipwzw** [comment]
3q
