### ISSUE TITLE
减少测试链上的fork 干扰正式系统

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#326]
对于在开发过程中，还没有上线的合约，只是用户测试链bug修复的情况下，这个fork 可以标记为 测试链专用的fork， 真实的链可以选择配置，也可以选择不配置。不会强制要求配置。（不配置表示默认启用）

如果合约已经正式上线了，这样的情况，那么必须要配置（系统为了安全，强制提醒配置）。

**Comment by linj-disanbo** [comment]
测试链的一些想法。 精简测试链， 一个是减少不必要交易和高度， 一个是保留各种交易类型的交易（足够的case）。 相当于把测试链做个一个测试的数据库， 又保证可以在可以在很短的时间验证完。同时，在测试链上的专有的fork 也是不需要存在了。
