### ISSUE TITLE
stat下部分接口不可用，相关的命令和结构体做移除

### ISSUE THREAD

**Issue by xies1031** [33cn/chain33#328]
**Describe the bug**
配置中启用stat的情况下，stat下部分接口不可用
![image](https://user-images.githubusercontent.com/44956625/51797967-7a836f80-2246-11e9-9166-150ed26fdc94.png)
![image](https://user-images.githubusercontent.com/44956625/51797972-85d69b00-2246-11e9-9b28-809a9a8101f6.png)
![image](https://user-images.githubusercontent.com/44956625/51797977-8ec76c80-2246-11e9-91de-974b63273ce1.png)
以上三个方法不可用

**Comment by vipwzw** [comment]
这些接口已经删除，写的有问题，会在下一个版本处理。

**Comment by vipwzw** [comment]
这些接口可能要移除掉，会通过 外部数据库做统计相关的工作。
