### ISSUE TITLE
chain33代码中存在大量的错误未处理，存在引起系统奔溃的风险

### ISSUE THREAD

**Issue by harrylee2015** [33cn/chain33#334]
**Describe the bug**
[chain33代码安全性检测](https://github.com/harrylee2015/share/blob/master/chain33/chain33%E4%BB%A3%E7%A0%81%E6%A3%80%E6%B5%8B%E5%88%86%E6%9E%90.md)

此外还存在部分方法圈复杂度过高，单元测试覆盖率不全的问题

**Comment by vipwzw** [comment]
错误处理检查完毕后，这个部分需要加入ci 检测

**Comment by andyYuanFZM** [comment]
这个我们可以先初步分析下， 量还比较大，有些还需要人工看一下。

**Comment by vipwzw** [comment]
嗯

**Comment by harrylee2015** [comment]
附上chain33,plugin 各个模块的安全扫描问题统计
https://confluence.33.cn/pages/viewpage.action?pageId=5971923

**Comment by harrylee2015** [comment]
```bash
Summary:
   Files: 345
   Lines: 90591
   Nosec: 0
  Issues: 654

```
重新扫描了一下，现在是654个有为处理的点，比之前降低了将近100个，我看了一下剩余的都是些low等级的错误处理，绝大多数是cmd某块，使用直接用_,丢弃掉了错误，还有些是proto buf自动生成的，都没什么风险

**Comment by vipwzw** [comment]
OK

**Comment by vipwzw** [comment]
plugin 中也扫描处理一下

**Comment by harrylee2015** [comment]
```bash
Summary:
   Files: 540
   Lines: 128035
   Nosec: 0
  Issues: 1245
```
我们这边已经处理过一次了，我扫描了一下，还有1000多个low等级的告警，我挨个扫看了一下，和chain33一样，绝大多数都是cmd和protobuf 自生成文件告警，没什么风险

**Comment by harrylee2015** [comment]
后期如果可以的话，可以用 #nosec  注释我们写的代码中已经手动排查过的告警，这样下次扫面就会自动屏蔽了

**Comment by andyYuanFZM** [comment]
chain33和plugin中的gosec问题已经处理。
