### ISSUE TITLE
在Exec中使用LocalDB 会引发bug

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#335]
我们知道，区块的执行顺序是 Exec -> 保存statedb -> ExecLocal -> 保存LocalDB，所以。如果你在Exec 中调用 LocalDB 读取到的很有可能是旧的数据，所以在目前的框架下面不用 在 Exec 中调用 LocalDB。

但是，statedb中，无法做列表查询，列表查询也会引起严重的性能问题。比如，一个游戏中，有10000个人参与，最后开奖的时候要做列表查询，这样大规模的列表在 statedb中基本上没有办法完成。直接卡死。

如果执行的顺序改成：

Exec -> ExecLocal  -> Save(statedb, localdb)

同时对ExecLocal的列表做一个归并，那么可以完美的解决这个问题。但是，对系统框架的影响要做一个评估。

**Comment by harrylee2015** [comment]
f3d中存在这样的问题

**Comment by harrylee2015** [comment]
这个问题修复了吗

**Comment by vipwzw** [comment]
还没有，还在处理中。估计本周可以修复。

**Comment by vipwzw** [comment]
为了兼容原来的系统，默认情况下，我们都采用：
Exec -> 保存statedb -> ExecLocal -> 保存LocalDB 这样的执行顺序。
但是，如果合约中执行了:
1. ExecutorOrder() 00  默认执行 
2. ExecutorOrder() 01 那么，默认都会在 每个 execTx 后，执行 execLocal。同时，在ExecLocal的时候，如果已经 有可 LocalKV , 那么不重复执行。
3. ExecutorOrder() 11，那么，执行 01 并且，ExecLocal 步骤的时候，还会重复执行每个 execLocal

**Comment by vipwzw** [comment]
比如
1. 计算所有交易的手续费等操作，和合约无关的操作。

2.  跨链交易中，平行链计算自己区块的成功失败表

我们需要重新设计这类需求的插件，需要增加一个新的插件类型。

**Comment by vipwzw** [comment]
为了解决这个bug，我们先做内部一个微调。
1. ExecutorOrder == 0 按照原来的结构执行，不改变
2. ExecutorOrder == 1 增加一个执行cache，这个执行cache 会被抛弃，不会存盘。
