### ISSUE TITLE
mac新版本cpu占用高

### ISSUE THREAD

**Issue by asinen** [33cn/chain33#342]
6.1版本通常cpu会占用在200%左右，调试窗口比原来要卡很多。望改进

**Comment by vipwzw** [comment]
你用的是 https://bityuan.com/wallet 这里的mac 版本吗？

**Comment by vipwzw** [comment]
提供一些高cpu的截图，还有你的苹果系统的版本

**Comment by asinen** [comment]
<img width="222" alt="2019-02-11 3 23 20" src="https://user-images.githubusercontent.com/3921721/52550008-20230b00-2e11-11e9-82f4-9f1df7080c90.png">
<img width="376" alt="2019-02-11 3 23 55" src="https://user-images.githubusercontent.com/3921721/52550009-20230b00-2e11-11e9-859e-6c8b7d29cdc7.png">
<img width="250" alt="2019-02-11 3 24 08" src="https://user-images.githubusercontent.com/3921721/52550010-20bba180-2e11-11e9-8e03-20ff57fa4b6b.png">
@vipwzw 望核实下

**Comment by vipwzw** [comment]
钱包整个截图一下，看看是不是在 同步过程中。

**Comment by asinen** [comment]
钱包早就同步好了，同步最新的那个块时间占比很小，程序占用cpu倒是一直没降。之前5.3没这个问题

**Comment by YingQm** [comment]
@asinen 1、是否可以提供活动监视器里面CPU排行的截图，想确认一下是chain33的CPU高，还是bityuan的CPU高？2、调试窗口比原来要卡很多，是具体某些命令返回结果慢，还是全部的命令都返回结果慢，还是界面卡住了，不响应？

**Comment by asinen** [comment]
知道原因了，不是开发的问题。
