### ISSUE TITLE
加速 mavl 树的方法

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#368]
在同步过程中，加速 mavl树的最有效办法是：

1. 把大部分数据都cache到内存中。
2. 减少写盘的次数。不一定每个区块都去写数据。可以每隔一定间隔，cache 一下数据。
3. mavl 有时候只是作为同步中的一个阶段，同步完成就会删除，所以，这个优化可以做一些特殊的处理。

**Comment by 33cn** [comment]
内存使用在 1G 以内，最好是 500M 以内

**Comment by vipwzw** [comment]
已经处理的差不多，目前有一个问题，就是用户重启节点，就会让节点的cache消失，从而大大减慢了执行。先关闭问题，目前没有更好的方案。
