### ISSUE TITLE
提升 执行器执行 交易时候的性能

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#369]
目前执行器执行交易有一个测试，在 executor 模块中。
```
BenchmarkExecBlock
```

测试还是比较慢，需要优化。

**Comment by vipwzw** [comment]
目前的结果如下
```
       3	 435761175 ns/op	171924389 B/op	 3151120 allocs/op
PASS
ok  	github.com/33cn/chain33/executor	8.854s
```

**Comment by vipwzw** [comment]
1万个交易 435ms, 需要分析时间占用情况，什么模块化的时间比较多，能不能做相应的优化。

**Comment by andyYuanFZM** [comment]
@harrylee2015  帮忙在程序中加点打印， 测试一下不同模块花的时间。 先出一个测试结果的分析报告。

**Comment by harrylee2015** [comment]
ok

**Comment by harrylee2015** [comment]
通过测试发现当store 配置merkle方式时， ExecKVMemSet，ExecKVSetCommit两个函数耗时比较多

https://github.com/harrylee2015/share/blob/master/chain33/chain33%E4%B8%ADexector%E4%B8%ADbenchmark%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95%E5%88%86%E6%9E%90.md

**Comment by vipwzw** [comment]
blockchain | ExecBlock | 132.450229ms

执行一个区块只花费 0.13s的情况，为什么tps 只有 700 左右 ？理论上来说，如果 ExecBlock 只有 0.13的话，tps 到 5000 应该没有问题，考虑分析一下 tps 上不去的原因

**Comment by harrylee2015** [comment]
这个是我电脑本地起的虚拟机，我换个好点的配置的机器，具体再测一下

**Comment by harrylee2015** [comment]
换了好点的配置，重新测了一下，数据已经更新了
https://github.com/harrylee2015/share/blob/master/chain33/chain33%E4%B8%ADexector%E4%B8%ADbenchmark%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95%E5%88%86%E6%9E%90.md

**Comment by andyYuanFZM** [comment]
当存储方式是mavl时， 比较耗时的是ExecKVMemSet，ExecKVSetCommit这两个地方，在这里对merkle树的处理占的时间会比较多。

**Comment by vipwzw** [comment]
这个阶段性能优化告一段落，后面可能还需要做一次优化。
