### ISSUE TITLE
资产列表方案

### ISSUE THREAD

**Issue by linj-disanbo** [33cn/chain33#379]
**Is your feature request related to a problem? Please describe.**
如何快速获得一个地址对应的资产列表？ 

**Describe the solution you'd like**
方案1. 目前token 在本地数据库加了相关资产的信息。 把这个方案推广到其他能参数资产的合约。 但部分合约如找回合约， 需要知道某地址的所有资产，如何依赖合约自己不记录资产情况， 将形成执行时， 依赖本地数据库。 

**Describe alternatives you've considered**

 1.  list state db  的方案是不行的， account key 的命名，地址在资产之后

**Comment by vipwzw** [comment]
#18  中已经做了一个方案，但是太慢

**Comment by vipwzw** [comment]
这个功能不提供了，用外接数据库解决这个问题。
