### ISSUE TITLE
使用plugin同步测试链，区块执行完成，但实际未写入

### ISSUE THREAD

**Issue by xies1031** [33cn/chain33#393]
使用plugin从0同步，区块0状态哈希校验不过
![image](https://user-images.githubusercontent.com/44956625/54106022-d75e7200-440f-11e9-9df6-84ffd9f8fad7.png)

**Comment by icehawk-hyb** [comment]
这个问题是最新的plugin软件执行区块0之后的状态hash和以前的不一致导致。util.go 文件中ExecBlock函数中的DelDupKey（）函数处理kv和以前blockchain/exec.go中kv的处理结果一样导致。将blockchain/exec.go中处理kv代码移植到util.go 文件中ExecBlock函数中就可以执行ok。

**Comment by vipwzw** [comment]
OK

**Comment by vipwzw** [comment]
fixed #396
