### ISSUE TITLE
设置 ./chain33 -datadir=data2 会发生panic

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#398]
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/util.ResetDatadir(0xc421b4c360, 0x7ffeefbffb63, 0x5, 0xc421c846f0, 0x2)
	/Users/kingwang/goprojects/src/github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/util/util.go:437 +0x7b6
github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/util/cli.RunChain33(0x1cdd373, 0x7)
	/Users/kingwang/goprojects/src/github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/util/cli/chain33.go:80 +0x107e
main.main()
	/Users/kingwang/goprojects/src/github.com/bityuan/bityuan/main.go:27 +0x9a
kingwangdeiMac:bityuan kingwang$ ./bityuan -datadir=./data2

**Comment by vipwzw** [comment]
@icehawk-hyb  看一下

**Comment by vipwzw** [comment]
./data2 这样就没有问题

**Comment by icehawk-hyb** [comment]
这个问题是传入字符串长度小于6个。而代码中是取0:6之间的值。越界导致。但我现在使用plugin的代码传入长度小于6的字符串没有报错。
![image](https://user-images.githubusercontent.com/44956735/55306982-9f83a100-5488-11e9-8925-465af08252ad.png)

**Comment by icehawk-hyb** [comment]
plugin也有这问题。需要校验一下长度就可以

**Comment by vipwzw** [comment]
@icehawk-hyb  处理一下
