### ISSUE TITLE
mempool是否有问题

### ISSUE THREAD

**Issue by libangzhu** [33cn/chain33#412]
目前查看各节点的mempool大小一致保持在100以上，但是观察最近打包的区块，交易非常少。刚才签名了一笔交易发送出去，等待了5分钟后才能被打包，另外 通过rpc 访问接口Chain33.Getmempool 无法获取数据
![image](https://user-images.githubusercontent.com/16385190/54355328-c9b91e80-4693-11e9-9f44-2bf31c09d5a4.png)
![image](https://user-images.githubusercontent.com/16385190/54355350-d76ea400-4693-11e9-8e16-befb6ba5dfcf.png)

![image](https://user-images.githubusercontent.com/16385190/54355363-e05f7580-4693-11e9-865f-6122aad991f0.png)

**Comment by vipwzw** [comment]
``` 
{
            "execer": "user.p.fzmtest.paracross",
            "payload": {
                "commit": {
                    "status": {
                        "mainBlockHash": null,
                        "mainBlockHeight": "0",
                        "title": "user.p.fzmtest.",
                        "height": "0",
                        "preBlockHash": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
                        "blockHash": "0xc9ee9fa066ef927f24fe879e98d06431719ce8ef61188179b55407e7044040bf",
                        "preStateHash": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
                        "stateHash": "0x2863c8dbc7fe3146c8d4e7acf2b8bbe4666264d658356e299e240f462a382a51",
                        "txCounts": 0,
                        "txResult": null,
                        "txHashs": [],
                        "crossTxResult": null,
                        "crossTxHashs": []
                    }
                },
                "ty": 0
            },
            "rawpayload": "0x0a9c010a99011a0f757365722e702e667a6d746573742e2a2000000000000000000000000000000000000000000000000000000000000000003220c9ee9fa066ef927f24fe879e98d06431719ce8ef61188179b55407e7044040bf3a20000000000000000000000000000000000000000000000000000000000000000042202863c8dbc7fe3146c8d4e7acf2b8bbe4666264d658356e299e240f462a382a51",
            "signature": {
                "ty": 1,
                "pubkey": "0x032777e96c68947da4dc2f30df4b2f1be5b71fe0c32f8114bc7467e63d1711a5b6",
                "signature": "0x304502210086b23277618b8631f7228359c205d740e5c322db14cc6a1502627664360c8d7002205cfb6e72dae7b5035d13c66ceb4042ffce12e4a883391305da36e9f6997b83af"
            },
            "fee": "0.0260",
            "expire": 0,
            "nonce": 6376962305247902834,
            "to": "16x5cTgn879dHbYTrJSRGJk233xVEsdvNX",
            "from": "1MCftFynyvG2F4ED5mdHYgziDxx6vDrScs",
            "groupCount": 20,
```
这笔交易的手续费是 0.026,但是账户余额只有 0.01

**Comment by vipwzw** [comment]
@icehawk-hyb  你来处理这个问题

**Comment by vipwzw** [comment]
应该是检查 TxGroup 相关手续费的时候，出问题了。

**Comment by vipwzw** [comment]
当个地址 现在 100 比交易，在mempool 中，但是，这个地址瞬间发的交易数目远远不止这个数目。
![image](https://user-images.githubusercontent.com/1617585/54369971-c7fe5380-46b1-11e9-8ebf-6d087ab03e3a.png)

**Comment by icehawk-hyb** [comment]
测试发现单笔交易和交易组，账户余额不够付手续费时mempool都没有校验掉。直到exec执行模块执行时才报费用不够丢弃这笔错误的交易。

**Comment by 33cn** [comment]
这是一个比较大的bug。但是，不能解释所有的现象

**Comment by icehawk-hyb** [comment]
412问题是如下几个bug一起引起

1，mempool没有将账户余额小于交易费用的交易过滤掉 （已经解决）
2，没有挖到矿的节点的共识模块积压了很多已经过期或者余额不足的交易在缓存中。当节点挖到矿之后这些交易会被从缓存中清除掉   （没有挖到矿的节点共识模块需要对积压的交易做一些过滤）
3，平行链的commit交易没有设置过期时间 （需要平行链设置commit交易的过期时间）
4，共识模块每个区块最大txs交易数量的检测没有生效，导致一个区块打入了超过最大数量的交易（已经解决）

问题分析：

步骤一：余额不足的错误交易进入mempool，并缓存在挖矿节点的共识模块中，

步骤二：此错误交易在mempool中过期或者超过10分钟没有被打包就会从mempool中丢弃，这样同一个账户下的交易又可以进入mempool中，新进入的交易又会被累计缓存在挖矿节点的共识模块中

步骤三：没有挖到矿的节点一直在累积缓存此错误交易，直到此交易被打包或者本节点挖到矿。

步骤四：积压了很久的交易在执行时有判断此交易是否过期的，过期的交易直接被删除不执行。但由于平行链的commit交易的过期时间设置的是0，也就是不过期。所以在账户有钱之后这些积压的交易都被执行成功了。

**Comment by vipwzw** [comment]
1. 挖矿模块定期2分钟，清除两类交易。

1.1. 已经过期的交易

1.2 余额不够支付手续费，或者少于10倍最小手续费。

**Comment by vipwzw** [comment]
@icehawk-hyb

**Comment by icehawk-hyb** [comment]
挖矿模块定期清除已经过期的交易时可以的，本生这个交易在mempool过期也会被清除的。

但是余额不够支付手续费，或者少于10倍最小手续费的交易在挖矿模块定期清除了，但是mempool中还是存在的，会再次被请求到挖矿模块这边的。感觉这种交易挖矿模块不需要清除掉，等有钱了这种交易就可以被执行了。
