### ISSUE TITLE
测试链的交易被广播至主网并打包

### ISSUE THREAD

**Issue by xies1031** [33cn/chain33#414]
测试链使用地址14KEKbYtKKQm4wMthSK9J4La4nAiidGozt向地址1K7Fko7e21F2qXdYriVLheJue5ZW5KerZL转币，主网上同样打包并执行了一次
![image](https://user-images.githubusercontent.com/44956625/54404061-40dec900-470d-11e9-82a1-e54a0fcfbe08.png)

**Comment by xies1031** [comment]
测试链：
![image](https://user-images.githubusercontent.com/44956625/54404138-87342800-470d-11e9-8418-ec061302de68.png)
主网：
![image](https://user-images.githubusercontent.com/44956625/54404240-cd898700-470d-11e9-8db7-c68d1ee3a02a.png)

**Comment by vipwzw** [comment]
@helpylee

**Comment by libangzhu** [comment]
处理中...

**Comment by xies1031** [comment]
测试网节点接收到了主网节点的广播
![image](https://user-images.githubusercontent.com/44956625/54795868-c07a1400-4c88-11e9-807b-f75078493054.png)
175W高度为主网高度

![image](https://user-images.githubusercontent.com/44956625/54795874-c5d75e80-4c88-11e9-9bf8-8fe5478470e2.png)
peerinfo中只看到了测试网节点

**Comment by xies1031** [comment]
更新后问题已修复
