### ISSUE TITLE
平行链无法使用send完成交易一步发送

### ISSUE THREAD

**Issue by xies1031** [33cn/chain33#427]
使用最新bityuan代码，在平行链上发送交易，无法使用send发送，返回节点未同步。
![image](https://user-images.githubusercontent.com/44956625/54672681-a0850c00-4b33-11e9-951e-c3479c11ae7a.png)
拆分成构造-签名-发送的三步流程可以发送成功。
平行链连接的节点是云端的节点集群，是同步的

**Comment by vipwzw** [comment]
袁子处理一下

**Comment by andyYuanFZM** [comment]
好的。

**Comment by harrylee2015** [comment]
看了一下代码这个不是问题，应该是发送交易的时候，主节点mempool 没有同步好，我搭了个环境试了一下，组合命令式可以用的
```bash 
harry@harry-VirtualBox:~/parachain$ ./chain33-cli send --paraName "user.p.guodun." config config_tx -c token-finsher -o add -v 1PUiGcbsccfxW3zuvHXZBJfznziph5miAo -k 14KEKbYtKKQm4wMthSK9J4La4nAiidGozt --rpc_laddr "http://localhost:8901"
0xcf17f58aa2ee631b55e1cdb4bf3353bbe9b074c5f79b5577730215e4756cda2b


```

**Comment by xies1031** [comment]
> 看了一下代码这个不是问题，应该是发送交易的时候，主节点 没有同步好，我搭了个环境试了一下，组合命令式可以用的
> 
> ```shell
> harry@harry-VirtualBox:~/parachain$ ./chain33-cli send --paraName "user.p.guodun." config config_tx -c token-finsher -o add -v 1PUiGcbsccfxW3zuvHXZBJfznziph5miAo -k 14KEKbYtKKQm4wMthSK9J4La4nAiidGozt --rpc_laddr "http://localhost:8901"
> 0xcf17f58aa2ee631b55e1cdb4bf3353bbe9b074c5f79b5577730215e4756cda2b
> ```

当时我连接的云端节点集群，是同步的，而且采用分步的方式可以完成交易发送

**Comment by andyYuanFZM** [comment]
我们也连云端节点试一下。

**Comment by harrylee2015** [comment]
我本地连了云端服务器，拉了一个harry 的平行链，可以发送的
```bash 
harry@harry-VirtualBox:~/harryParachain$ ./chain33-cli send --paraName "user.p.guodun." config config_tx -c token-finsher -o add -v 1PUiGcbsccfxW3zuvHXZBJfznziph5miAo -k 14QoUY4VrL75anfjW5Eeodoobv7JhrHNkW  --rpc_laddr "http://localhost:8901"
0xed1b69079a30525bb2ea95cc7c3e4da070a3547b9b8acfd8ed3427d896c2e6df
```

**Comment by harrylee2015** [comment]
![image](https://user-images.githubusercontent.com/18208851/54811140-dd333d80-4cc2-11e9-82bc-f8959b6178d4.png)

**Comment by xies1031** [comment]
> 我本地连了云端服务器，拉了一个harry 的平行链，可以发送的
> 
> ```shell
> harry@harry-VirtualBox:~/harryParachain$ ./chain33-cli send --paraName "user.p.harry." config config_tx -c token-finsher -o add -v 1PUiGcbsccfxW3zuvHXZBJfznziph5miAo -k 14QoUY4VrL75anfjW5Eeodoobv7JhrHNkW  --rpc_laddr "http://localhost:8901"
> 0x913699dfded6be1bda5cb82bd8f5229030ff0eb102f37a91f81667006981bc6e
> ```

平行链chain33有更新过吗？我用的是发给国盾的文档里的版本

**Comment by harrylee2015** [comment]
可能之前的版本有问题吧

**Comment by xies1031** [comment]
用最新版本无法复现，先关闭
