### ISSUE TITLE
测试链增加assets参数后，BTY转账的symbol显示为小写

### ISSUE THREAD

**Issue by xies1031** [33cn/chain33#450]
测试链增加assets参数后，BTY转账的symbol显示为小写：
![image](https://user-images.githubusercontent.com/44956625/55391417-e5656580-556b-11e9-8aa6-4dc191f29c4b.png)
symbol需固定为大写
@linj-disanbo

**Comment by linj-disanbo** [comment]
@xies1031  18BTY 和 手续费是通过什么接口得到的大写的BTY
@vipwzw  现在资产返回的是直接用计算帐号里的symbol 。  平行链可以配置主币的symbol， 如果返回不一致可能会引起误解。 bty 是否需要强制改为大写或其他地方有大写的BTY统一改为小写？

**Comment by vipwzw** [comment]
bty 历史原因已经是小写。接口返回给用户的时候可以全部大写，但是，在数据库里面是小写。
