### ISSUE TITLE
平行链mempool bug

### ISSUE THREAD

**Issue by niniwzw** [33cn/chain33#474]
![image](https://user-images.githubusercontent.com/8331612/56456934-f4d71200-63a5-11e9-848c-4ee2af6ba1da.png)

**Comment by andyYuanFZM** [comment]
@lynAzrael  这个问题帮忙处理下。 
问题发生的原因： 交易直接发送到平行链的mempool中去了，目前平行链的mempool不处理交易，所以会返回这个error.
改造方法：
1. 改造平行链上的mempool的逻辑，平行链收到交易后，转发到主链的mempool.
2. 处理主链返回的错误，给客户端显示。

**Comment by lynAzrael** [comment]
好的

**Comment by andyYuanFZM** [comment]
验证通过， 增加平行链mempool功能。
