### ISSUE TITLE
主链mempool 导致的panic 

### ISSUE THREAD

**Issue by libangzhu** [33cn/chain33#475]
队列超时
panic: ErrQueueTimeout

goroutine 61 [running]:
github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/queue.(*client).Wait(0xab492c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/mnt/xsTest/src/github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/queue/client.go:132 +0x13d
github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/system/mempool.(*Mempool).checkTxListRemote(0xa8b8960, 0x1e11dc70, 0x31a40010, 0x1, 0x2)
	/mnt/xsTest/src/github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/system/mempool/check.go:39 +0x1fe
github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/system/mempool.(*Mempool).checkTxRemote(0xa8b8960, 0x8a9a0e3, 0x7, 0x1, 0x0, 0xd87ad8c, 0x0, 0x8a80660, 0x1e0f6300, 0x0, ...)
	/mnt/xsTest/src/github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/system/mempool/check.go:140 +0x220
github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/system/mempool.(*Mempool).pipeLine.func2(0x8a9a0e3, 0x7, 0x1, 0x0, 0xd87ad8c, 0x0, 0x8a80660, 0x1e0f6300, 0x0, 0x0, ...)
	/mnt/xsTest/src/github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/system/mempool/eventprocess.go:41 +0xaa
github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/system/mempool.step.func1(0xa832400, 0xa8321c0, 0xac72148, 0xa9ede80)
	/mnt/xsTest/src/github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/system/mempool/pipeline.go:21 +0xb0
created by github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/system/mempool.step
	/mnt/xsTest/src/github.com/bityuan/bityuan/vendor/github.com/33cn/chain33/system/mempool/pipeline.go:17 +0x61

![image](https://user-images.githubusercontent.com/16385190/56478994-4803ae80-64e5-11e9-92d4-2ad27799dfc6.png)

**Comment by icehawk-hyb** [comment]
[txcheck.log](https://github.com/33cn/chain33/files/3102527/txcheck.log)
![042df06e76afe30e3c305551e0fd1e1](https://user-images.githubusercontent.com/44956735/56488014-ad6c9500-650f-11e9-955a-bbf218300043.png)

问题分析：
从日志看最后一次收到EventCheckTx时间是在22:02:10.但整个日志的最后记录时间是22:02:11    。相差也就是1秒不应该超时。怀疑chain33任务出问题了，

**Comment by icehawk-hyb** [comment]
[mempanic.tar.gz](https://github.com/33cn/chain33/files/3102626/mempanic.tar.gz)

**Comment by vipwzw** [comment]
这个问题后面有解决吗？

**Comment by icehawk-hyb** [comment]
这个问题从日志看，感觉是chain33任务异常了，或者是chain33任务休眠了导致的。后面没有才出现过。
