### ISSUE TITLE
交易组构造时过期时间及手续费相关修改

### ISSUE THREAD

**Issue by xies1031** [33cn/chain33#480]
过期时间：
目前的交易组构造签名时，默认的过期时间设置为0，需修改为其中每个交易分别有300s过期时间；
手续费：
目前的交易组签名时，设置手续费无效， 需修改为能针对交易组第一笔交易设置手续费。
@icehawk-hyb

**Comment by icehawk-hyb** [comment]
目前看在sign阶段无法修改交易组的过期时间和费用。因为过期时间和费用的修改会导致本交易的hash变化了，从而导致整个交易组出错。交易组的过期时间和费用设置只能在构建交易组时设置。构建完交易组之后，交易组信息不能被修改。

**Comment by icehawk-hyb** [comment]
目前平行链的交易组无法支持按照区块高度设置过期时间。
1，过期时间按照主链的高度设置，此交易在平行链上过期时间检测会不过。毕竟平行链的当前高度远远低于主链当前高度。
2，过期时间按照平行链的高度设置，这个交易组在主链这边就会检测不过。
