### ISSUE TITLE
建议在构造代扣手续费的rpc接口上增加对多笔交易的代扣

### ISSUE THREAD

**Issue by libangzhu** [33cn/chain33#492]
![image](https://user-images.githubusercontent.com/16385190/56858017-89dd9a80-69a6-11e9-8f1e-b01b8b7df310.png)

txHex 现在是string格式的，可以搞成[]string数组格式，这样可以满足同时多笔代扣需求

**Comment by vipwzw** [comment]
新增加一个接口，这个接口保持不变。

**Comment by vipwzw** [comment]
就用： CreateTxGroup  这样函数吧。 注意代扣的可能是多个人的交易，不是仅仅是一个人的交易。考虑一下这样的场景。

**Comment by libangzhu** [comment]
好的

**Comment by libangzhu** [comment]
> 文档添加了吗？doc.33.cn 上

已经添加了
