### ISSUE TITLE
建议钱包rpc接口增加钱包导出导入账户列表的功能

### ISSUE THREAD

**Issue by libangzhu** [33cn/chain33#495]
在实践中，有时候需要删除数据，重新创建钱包，这时候，之前创建的钱包地址+钱包lable都会消失，如果有个rpc可以导出这些账户列表，删除钱包之后，通过导入账户接口，就可以恢复之前创建的地址列表。

**Comment by vipwzw** [comment]
是不是就是账户列表的接口

**Comment by purplieee** [comment]
我用的优盾钱包，接入数字资产非常快速便捷
