### ISSUE TITLE
修正接收地址校验

### ISSUE THREAD

**Issue by xies1031** [33cn/chain33#496]
目前的to addr的校验有些问题，比如连续输入两次的地址，依然能够执行成功
![image](https://user-images.githubusercontent.com/44956625/56884549-be338280-6a9c-11e9-8e98-9f27417a5a70.png)
增加地址校验
@icehawk-hyb

**Comment by icehawk-hyb** [comment]
测试链0x901834a656905d6fc6e71b3e1ad8f509001e12758a8fcf65dc6174b2faf19139交易上报ErrCheckChecksum错误。，所以需要定义新的错误码

**Comment by vipwzw** [comment]
已经合并
