### ISSUE TITLE
chain33 是否考虑使用 go mod 管理模块

### ISSUE THREAD

**Issue by linj-disanbo** [33cn/chain33#528]
go 1.13 预计将在8月份完成， mod 作为默认支持，GOPATH 等将被禁用

**Comment by vipwzw** [comment]
考虑在 6.3 版本支持

**Comment by harrylee2015** [comment]
@linj-disanbo @vipwzw  这个版本我本地测了一下基本功能，没有问题，后续如果合入的话，可能需要CI那边相应做一下微调，你们检视一下
