### ISSUE TITLE
rpc 对异常请求数据会发生panic

### ISSUE THREAD

**Issue by libangzhu** [33cn/chain33#534]
![image](https://user-images.githubusercontent.com/16385190/58153588-01e76980-7ca2-11e9-99a9-0b6c9a936b22.png)
如果我用非json格式的数据请求jiek接口调用，parseJSONRpcParams接口会返回一个err信息，同时client变量是nil，在err处理的过程中，没有异常返回，并且在接下来的代码中使用了空指针，导致rpc服务启动这个goroutine panic掉。接口调用方也没有任何错误消息返回

**Comment by libangzhu** [comment]
![image](https://user-images.githubusercontent.com/16385190/58153989-1a0bb880-7ca3-11e9-893e-5ba7f9041ceb.png)

**Comment by 33cn** [comment]
尽快修复一下，查看一下 grpc 是否有相似的错误。让 @bysomeone  来处理吧
