### ISSUE TITLE
无法从对端peer同步数据，peer_info中可以看到对端节点，但同步数据时GetActivePeers可能没有此peer节点

### ISSUE THREAD

**Issue by icehawk-hyb** [33cn/chain33#542]
**Describe the bug**
目前在pos33的测试环境中发现一个节点一直无法同步。

**To Reproduce**
没有找到重现步骤和方法，但已经在不同的环境中出现过几次同样的问题。提个issues跟踪此问题

通知日志看到：A节点无法同步B节点的数据，但可以收到B节点的一部分广播数据。
A节点的peer_info中有B节点，但是在同步数据时GetActivePeers 中可能没有B节点。导致数据没有同步过来。怀疑可能是peer_info和GetActivePeers的数据没有保持一致
[chain33.log](https://github.com/33cn/chain33/files/3246174/chain33.log)

**Comment by bysomeone** [comment]
经过测试分析，由于局域网内NAT映射可能失败，节点在上传自身地址时只是临时内网地址，而代码中用该地址作为节点信息管理的key，在实际调用GetActivePeer时，并不能获取到实际的节点，导致不一致
