### ISSUE TITLE
系统rpc测试失败-交易创建

### ISSUE THREAD

**Issue by mdj33** [33cn/chain33#545]
chain33_CreateRawTransaction fail
chain33_CreateTransaction fail
chain33_CreateNoBalanceTransaction fail

@icehawk-hyb

**Comment by vipwzw** [comment]
@mdj33  rpc 测试还没有开启马？

**Comment by vipwzw** [comment]
这个问题尽快解决

**Comment by mdj33** [comment]
这几个chain33　ｃａｓｅ都通过了，平行链还不稳定，框架重新调整了一下，正在通知大家按新的方法来
