### ISSUE TITLE
cli构造交易时自动获取合适的手续费

### ISSUE THREAD

**Issue by xies1031** [33cn/chain33#561]
目前构造交易时，拉取的是最低手续费0.001。因为6.2版本使用阶梯手续费，交易数量超过阈值时会导致最低手续费的交易无法发送，需要通过查询获取合适的手续费。
修改cli，让构造交易时的手续费使用合适的手续费。

**Comment by vipwzw** [comment]
这个事件接口做一个调整：
![image](https://user-images.githubusercontent.com/1617585/59488036-01ad4900-8eb1-11e9-9f7d-6ea6ef10f324.png)
增加一个准备发送的交易的数量，比如我要发送200比交易，现在mempool中的数目为0，那么实际上我的手续费要保证 200才能正确计算。还有一个参数是准备发送交易的size，也作为手续费计算的参考

**Comment by vipwzw** [comment]
详细的规则问一下xs 或者 cdh
