### ISSUE TITLE
chain33主网配置文件相关

### ISSUE THREAD

**Issue by yuexk** [33cn/chain33#603]
按照官方网站给定的配置文件，在运行的时候出现panic: Unsupported mempool type: ErrNotFound 错误，这个是什么问题？怎么解决？

panic: Unsupported mempool type: ErrNotFound

goroutine 1 [running]:
github.com/33cn/chain33/mempool.New(0xc000032910, 0xc001a57080, 0x16, 0x3)
	/Users/xikun.yue/gopro/src/github.com/33cn/chain33/mempool/mempool.go:13 +0x1d4
github.com/33cn/chain33/util/cli.RunChain33(0x0, 0x0)
	/Users/xikun.yue/gopro/src/github.com/33cn/chain33/util/cli/chain33.go:149 +0x84f
main.main()
	/Users/xikun.yue/gopro/src/github.com/33cn/chain33/cmd/chain33/main.go:16 +0x29

**Comment by andyYuanFZM** [comment]
配置文件[ mempool]标签 name 填的是什么？  
chain33的版本是从哪边获取的？

**Comment by yuexk** [comment]
配置文件是从这里获取的：https://chain.33.cn/document/121
这是[mempool]的相关配置：
# mempool队列配置其实对于打包节点才有效
[mempool]
# 每个账户在mempool中得最大交易数量，默认100
maxTxNumPerAccount=100

这个需要怎么解决，或者说可否提供一下主网的配置文件？

**Comment by yuexk** [comment]
> 配置文件[ mempool]标签 name 填的是什么？
> chain33的版本是从哪边获取的？

配置文件是从这里获取的：https://chain.33.cn/document/121
相关的参数配置是：
`
# mempool队列配置其实对于打包节点才有效
[mempool]
# 每个账户在mempool中得最大交易数量，默认100
maxTxNumPerAccount=100
`

**Comment by andyYuanFZM** [comment]
如果是搭建BTY主链：

版本获取，使用目前新发布的release-6.2.1版本：   
https://github.com/bityuan/bityuan/tree/release-6.2.1

配置文件使用以下
https://github.com/bityuan/bityuan/blob/release-6.2.1/bityuan.toml

官方文档上跟目前版本有些出入，我们更新下。

**Comment by yuexk** [comment]
> 如果是搭建BTY主链：
> 
> 版本获取，使用目前新发布的release-6.2.1版本：
> https://github.com/bityuan/bityuan/tree/release-6.2.1
> 
> 配置文件使用以下
> https://github.com/bityuan/bityuan/blob/release-6.2.1/bityuan.toml
> 
> 官方文档上跟目前版本有些出入，我们更新下。

好的，谢谢
