### ISSUE TITLE
网站上的api文档描述，有个地方错了

### ISSUE THREAD

**Issue by liueleven** [33cn/chain33#608]
可不可以领取bug奖励？？？？

网址：https://chain.33.cn/document/94#1.2%20%E9%92%B1%E5%8C%85%E8%A7%A3%E9%94%81%20Unlock

http://ww1.sinaimg.cn/large/006HEM6Bgy1g52xoba9cyj32jo19ogvq.jpg

**Comment by andyYuanFZM** [comment]
👍多谢，已经修改。
奖励主要针对chain33或plugin开源代码中BUG的发现 。
