### ISSUE TITLE
一个合约 在另外一个合约中的资产转移问题

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#643]
在我们的账户体系中，资产的转移都是通过私钥签名，但是合约没有私钥，比如，发展基金账户如果是一个合约，那么挖矿的用户怎么样把币转移到这个合约中。

我们抽象为：

合约1.合约2 -> 合约2.合约2

这类支持的转移需要定义特殊的规则。

1. 任何一个私钥都可以转移这个资产
2. 资产必须一次性的转移，不允许填写数量
3. 合约2.合约2 -> 合约1.合约2 是不能转移的。也就是只允许转移到 contract.contract 名字相同的合约。
4. 需要提供合约的名字。合约名字必须是 user.* 或者内置合约 （合约2这个地址不是一个普通地址，是真的合约地址）IsAllowExec 并且 ExecAddress(合约名字2) == 合约2

**Comment by 33cn** [comment]
暂时不做考虑。用其他的解决方案。
