### ISSUE TITLE
mempool增加最大交易费率配置项

### ISSUE THREAD

**Issue by bysomeone** [33cn/chain33#695]
* 目前mempool已经有maxTxFee配置，但用途有点不明确
* minTxFee含义是最小费率，代码里maxTxFee和Exec子配置maxExecFee有流程交互，maxExecFee标识总最大交易费

需要再梳理下相关逻辑含义，6.3相关暂时写死0.1最大交易费率

**Comment by vipwzw** [comment]
maxTxFee 应该是最大的手续费，不是费率。我们取名字的时候，把手续费和手续费费率搞混淆了。

**Comment by vipwzw** [comment]
系统做了限制不管手续费费率 和 交易的大小是多少，整体的手续费不能超过10

**Comment by vipwzw** [comment]
原来设计的时候，把mempool 的手续费 和 共识的手续费 两个分开了，现在看来没有必要，可以整体上弄一个 手续费的配置。应该是：minTxFeeRate maxTxFeeRate 以及 maxTxFee 三个配置。其他的配置可以都弄掉。
