### ISSUE TITLE
区块推送增加支持切换节点可以继续推送的功能

### ISSUE THREAD

**Issue by linj-disanbo** [33cn/chain33#714]
**Is your feature request related to a problem? Please describe.**

由于节点数据损毁/云节点到期/数据删除重新同步等，在现有的机制下，需要重新同步。 增加能从已经同步点继续同步的功能。 

**Describe the solution you'd like**
 增加能从已经同步点继续同步的功能。 

在注册推送点时， 增加参数表示已经推送的位置。

 1. 如果推送的位置在主链分支上，继续同步
 1. 如果在本节点不存在的位置，则需要调整同步点

调整同步点
 1. 注册请求的回复中，添加在已经同步高度附近区块（高度和hash）供选择
 1. 注册方， 调整同步点， 继续注册。注册方在成功注册后， 需要根据同步点，删除部分数据。

**Comment by vipwzw** [comment]
能详细说一下，在分叉链的情况下，同步的步骤。以及需要多少次的交互。

**Comment by linj-disanbo** [comment]
节点注册请求的回复给出的已经同步高度附近区块供选择
```
  区块信息包含 高度 哈希; 以及向前的N个区块的信息; (可以附加跳着变化的先前N个区块的信息（减少交互次数）)
  如在 1500000高度， N=100：   提供 1499900-1500000 区块信息， （1499800， 1499700 ...）
```

注册方：
```
 找出已经同步区块信息中和供选择的同步点的最大的公共区块，做为同步开始位置，继续注册。 
 没有公共区块的话， 以供选择高度最小的区块信息进行注册， 以要到更前面的区块信息。

 注册成功后， 根据同步点， 清理自己的部分分叉的数据。
```

需要多少次的交互： 主要和分叉的深度相关。

**Comment by linj-disanbo** [comment]
参数说明：支持三种情况 文档： https://chain.33.cn/document/97

不填新参数， 从0零开始推送。
 1. 填写Last 三个参数， 注册用last sequence 开始推送， 不匹配，返回推荐点
 1.  填写height/hash， sequence 为 -1, 返回推荐点height/hash 对应的推送点。 再次注册
 1. 填写height/hash， sequence 为 -1, 返回推荐点height/hash 对应的推送点。 再次注册

**Comment by linj-disanbo** [comment]
pr： https://github.com/33cn/chain33/pull/715
