### ISSUE TITLE
钱包锁的管理

### ISSUE THREAD

**Issue by yanyanhong** [33cn/chain33#718]
**Describe the bug**
当钱包是全解锁状态时，不能将walletlock 改变为ticketlock
**To Reproduce**
1. 钱包全解锁状态（walletLock：false，ticketLock：true）
2. 调用unlock  （walletorticket）传   true，只解锁ticket买票功能
3. 查看当前钱包状态 显示为 walletLock：false，ticketLock：false

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vipwzw** [comment]
何玉斌，你看一下怎么处理一下降级的问题

**Comment by icehawk-hyb** [comment]
起初的设计就是wallet锁级别高于ticket锁。
wallet解锁之后所有转账，买票都可以操作。
在wallet锁住时，可以通过ticket解锁来实现只开通买票的功能，此时转账是不允许的。

在wallet解锁的情况下通过解锁ticket锁来操作wallet锁状态有点不太合理，操作低级别锁影响了高级别的锁的状态。
针对这个问题的场景：可以先将wallet锁住，再解锁ticket就可以了
