### ISSUE TITLE
挖矿-委托挖矿-建议完善接口

### ISSUE THREAD

**Issue by yanyanhong** [33cn/chain33#721]
**Describe the bug**
     1、通过地址查询当前地址所属角色（委托者、被委托者）
     2、通过地址查询当前地址（当前地址为被委托者）的授权对象列表以及相应的授权挖矿数量

**Comment by linj-disanbo** [comment]
已经补充
https://chain.33.cn/document/99

**Comment by yanyanhong** [comment]
看到了，但是还缺个授权挖矿数量

**Comment by linj-disanbo** [comment]
> 看到了，但是还缺个授权挖矿数量

是这个， 绑定挖矿并可以指定数量

https://chain.33.cn/document/99#1.2%20%E7%BB%91%E5%AE%9A%E6%8C%96%E7%9F%BF%E5%9C%B0%E5%9D%80%20CreateBindMiner
