### ISSUE TITLE
挖矿--挖矿票数

### ISSUE THREAD

**Issue by yanyanhong** [33cn/chain33#722]
**Describe the bug**
获取每张票的当前的详细状态（eq：解冻时间）

 原因：给用户可选择释放ticket的精确票数和等待时间

**Comment by vipwzw** [comment]
@mdj33 和你前几天解决的ticket 列表类似，这个问题是不是已经解决了。

**Comment by mdj33** [comment]
> @mdj33 和你前几天解决的ticket 列表类似，这个问题是不是已经解决了。

是的，之前ticket list 已经可以获取所有状态的的ticket，　返回信息里面有opentime和minertime，可以推算等待时间
