### ISSUE TITLE
挖矿 - 热钱包节点损毁， seed丢失的情况下

### ISSUE THREAD

**Issue by linj-disanbo** [33cn/chain33#723]
过程： A 绑定 B挖矿 ， B seed 丢失 并 节点损毁。 需要A 导入热钱包， 关闭挖矿， 再重新绑定C挖矿。
希望可以通过A绑定 C挖矿， 由C来处理原来B帮A买的票。 而不是将A 导入热钱包

**Comment by vipwzw** [comment]
应该是可以通过 A 解绑 B 挖矿，再重新绑定 C

**Comment by linj-disanbo** [comment]
这样无法处理原来由B买的票。 close B买的票， 需要B或A来close

> 应该是可以通过 A 解绑 B 挖矿，再重新绑定 C

```
//check from address
		if action.fromaddr != ticket.MinerAddress && action.fromaddr != ticket.ReturnAddress {
			return nil, types.ErrFromAddr
		}
```

**Comment by vipwzw** [comment]
需要先 用 A close 掉所有的票才行。目前这一操作应该是不会有问题的，原来有人丢过。

**Comment by linj-disanbo** [comment]
具体步骤

 1.  先在另外的节点找出A所有的票
 1. 构建close ticket 交易
 1. 把交易让冷钱包（A) 签名
 1. 把签名好的交易， 发到区块链上， 关掉ticket 
 1. 再A 绑定C 挖矿

中间如何冷钱包交互和 A 绑定B挖矿的交互可以一样。
