### ISSUE TITLE
挖矿 - 接口挖矿补充 

### ISSUE THREAD

**Issue by linj-disanbo** [33cn/chain33#724]
**Describe the bug**
地址 https://chain.33.cn/document/99 

原来 ticket open/miner/close 做在钱包里， 没有接口文档

**Comment by vipwzw** [comment]
获取执行器地址 ConvertExectoAddr 这个接口放在这个分类下面不合适，应该是属于全局的接口

**Comment by linj-disanbo** [comment]
> 获取执行器地址 ConvertExectoAddr 这个接口放在这个分类下面不合适，应该是属于全局的接口

迁移到执行器接口
https://chain.33.cn/document/218

**Comment by linj-disanbo** [comment]
挖矿交易补充到 https://chain.33.cn/document/99
