### ISSUE TITLE
接口返回和接受的16进制不统一了

### ISSUE THREAD

**Issue by linj-disanbo** [33cn/chain33#746]
**Describe the bug**
 1.  部分接口返回的交易16进制带0x， 部分不带
 1. 接受交易的接口有只接受不带的，也有同时接受带和不带的
导致部分返回带0x的交易， 不能被某些接口接受

找到返回/输入不带0x接口
 1. CreateRawTransaction
 1. ReWriteRawTx
 1. CreateRawTxGroup
 1. CreateNoBlanaceTxs
 1. CreateNoBalanceTransaction
 1. GetHexTxByHash
 1. CreateTransaction

其余带0x的接口

**Expected behavior**
统一输入输出： 建议返回都加上0x， 输入接受两种

**Comment by 33cn** [comment]
用 common.FromHex 这个函数就统一了

**Comment by 33cn** [comment]
你来解决这个问题把。
