### ISSUE TITLE
同步区块链数据到mysql等外部环境处理

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#75]
# 外部程序如何实时的处理区块链的数据
我们提供了一个 blockchain seq 的接口，可以通过轮询的方式，实时的获取数据。通过这个方式，可以把数据同步到mysql 中。这个程序可以完全独立于blockchain ，类似mysql 和 blockchain的一个桥梁。如果用go直接完成整个同步应该不会有问题，但是，个人认为我们应该运行 php, nodejs 之类的擅长网页开发的脚本来做这个事情，比较好的办法是，同步好一个快以后，通知 PHP ，Nodejs 的一个callback 接口，PHP 和 nodejs 通过这个callback 接口 进一步处理数据，处理完成后，返回ok，或者调用done接口，通知这个桥接程序，已经处理完成。通知总是按照 seq的顺序通知，如果客户端没有正确标记，就会一直通知这个seq。

**Comment by vipwzw** [comment]
接口:
```
AddBlockSeqCB("name", "url")
```
相同的名字，添加两次，会覆盖上一次的url，默认最多添加20个不同name 的callback
如果要删除，那么就把url设置位空

设置某个seqid 已经处理完成
```
SetBlockSeqDone("name", seqid), 上次done 的id + 1 = seqid 才能成功
```

**Comment by vipwzw** [comment]
如果发生对方设置的url 不可用的情况，比如请求超时之类的，处理保证下面的要求:
1. 如果URL 处理出错，那么sleep 10s 后，继续 retry
2. 如果url处理成功，那么接着发送下一个seq的内容

**Comment by jixingwei** [comment]
是否可以采用开源的消息队列，外部程序订阅一个消息，chain33的seq增长以后主动推送，实际推送的数据就存到了外部程序的本地节点。

**Comment by vipwzw** [comment]
不需要搞的这样重，这个程序的实现不会超过100行代码

**Comment by jixingwei** [comment]
嗯，有些重量级。PUSH过去的消息是否存储可以由外部应用决定

**Comment by vipwzw** [comment]
还需要增加命令行，单元测试与集成测试，以及rpc接口。
同时 可以测试一下20个hook 加上去会不会影响性能。
