### ISSUE TITLE
给系统加上性能与状态的监控

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#750]
参考以太坊监控的内容，结合我们系统的实际情况，确定要监控的内容。

参考链接：
https://github.com/rcrowley/go-metrics
https://github.com/ethereum/go-ethereum/blob/master/ethdb/leveldb/leveldb.go#L61
https://github.com/ethereum/go-ethereum/tree/master/metrics

**Comment by zhengjunhe** [comment]
已经完成，添加了metrics，在go-leveldb进行监控，同时把采集到的数据发送到influxdb
