### ISSUE TITLE
jrpcclient和grpcclient数据返回结果不同

### ISSUE THREAD

**Issue by hxzqlh** [33cn/chain33#752]
jsonrpc 的 `QueryTransaction` 做了额外处理，grpc 的却没有，两种client 调用，返回结果不一致。建议统一返回结果。

`jrpchandler.go`
```
func (c *Chain33) QueryTransaction(in rpctypes.QueryParm, result *interface{}) error {
	var data types.ReqHash
	hash, err := common.FromHex(in.Hash)
	if err != nil {
		return err
	}

	data.Hash = hash
	reply, err := c.cli.QueryTx(&data)
	if err != nil {
		return err
	}

	transDetail, err := fmtTxDetail(reply, false)
	if err != nil {
		return err
	}

	*result = transDetail

	return nil
}
```

`grpchandler.go`
```
func (g *Grpc) QueryTransaction(ctx context.Context, in *pb.ReqHash) (*pb.TransactionDetail, error) {
	return g.cli.QueryTx(in)
}
```

**Comment by 33cn** [comment]
grpc 也需要提供 TransactionDetail 相关的字段。

**Comment by bysomeone** [comment]
#### 造成jrpc和grpc不一致原因，追溯了下
1. 一方面pb自动生成的代码json标记含有omit关键字，导致在jsonrpc序列化时，字段为零值时，字段会被忽略，造成前端解析缺失，因此把TransactionDetail涉及的所有结构，在rpc/types中均重新定义了相关的结构
2. 前端格式化展示需求，在重定义的结构增加了若干辅助性参数，如feefmt （此类需求建议放在前端格式化处理，或者另外定义接口，直接修改容易造成兼容性问题）
3. 之前考虑到grpc通常直接和程序代码对接，没有进行同步修改

#### 修改方法
1. 目前区别在于grpc缺失相关辅助性格式化字段
2. 可能需要将涉及的所有结构，再用protobuf定义一遍，修改接口的返回值为新的TransactionDetail

@vipwzw

**Comment by linj-disanbo** [comment]
补充一点： 部分 []byte 类型， 如hash， 在jsonrpc中是转换为 16进制字符串的

**Comment by vipwzw** [comment]
引用的pr 补充一下

**Comment by 33cn** [comment]
格式化的一些字段交给前端处理吧，grpc 已经返回了所有用户需要的信息
