### ISSUE TITLE
区块重复广播

### ISSUE THREAD

**Issue by icehawk-hyb** [33cn/chain33#760]
**Describe the bug**
A节点广播出去的区块，又被相连的节点广播回来了。导致了网络间的重复广播
**To Reproduce**

**Expected behavior**

A节点广播区块block-a给B节点，此时B节点再次广播时应该过滤掉A节点，不需要再广播给A节点

[广播出去的区块又被广播回来了.txt](https://github.com/33cn/chain33/files/4009477/default.txt)
[chain33-2019-12-30T13-00-49.543.log.gz](https://github.com/33cn/chain33/files/4009478/chain33-2019-12-30T13-00-49.543.log.gz)

@bysomeone 
。

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bysomeone** [comment]
这个是什么版本日志数据

**Comment by vipwzw** [comment]
6.3.3

**Comment by bysomeone** [comment]
看日志应该不是最新的比特元版本

**Comment by vipwzw** [comment]
最新版本已经解决这个问题了吗？

**Comment by bysomeone** [comment]
1. 关于发送过滤，6.3版本应该就已经处理了
2. 这个日志现象可能是之前广播的bug引起的

**Comment by vipwzw** [comment]
@bysomeone  之前的节点跑不了吧。

**Comment by bysomeone** [comment]
6.3.2 bityuan依赖4180fe9f0aba的chain33， 相关的交易广播代码

![image](https://user-images.githubusercontent.com/11565373/71872416-4d7a5500-3157-11ea-955b-d5f05ec08f73.png)

即日志中不可能出现isLightSend和ignoreSend同时为true情况

但在上述日志中可以匹配到相关的日志
![image](https://user-images.githubusercontent.com/11565373/71872536-b5c93680-3157-11ea-9a6c-dc7424ed247f.png)

用最新@xies1031 编的6.3.2跑的日志分析，未匹配到相关日志
![image](https://user-images.githubusercontent.com/11565373/71872641-06d92a80-3158-11ea-8866-683fa7e18462.png)

基本可以确定是编译的版本不对 @vipwzw  @icehawk-hyb
