### ISSUE TITLE
按照官方文档https://chain.33.cn/document/129搭载好联盟链后出现问题

### ISSUE THREAD

**Issue by HowardHub** [33cn/chain33#795]
我按照官方文档，搭载了含有4个节点的联盟链，并启动各个节点。
可是当我执行./chain33-cli net is_sync命令时，
出现以下错误提示：
Post https://localhost:8801: dial tcp [::1]:8801: connect: connection refused
请问有什么解决办法吗？

**Comment by YingQm** [comment]
官方文档中第5步有问题，已经修改了，重新试一下。

**Comment by YingQm** [comment]
> 我按照官方文档，搭载了含有4个节点的联盟链，并启动各个节点。
> 可是当我执行./chain33-cli net is_sync命令时，
> 出现以下错误提示：
> Post https://localhost:8801: dial tcp [::1]:8801: connect: connection refused
> 请问有什么解决办法吗？

官方文档中第5步有问题，已经修改了，重新试一下。

**Comment by YingQm** [comment]
官方文档中第5步有问题，已经修改了，请重新尝试一下。

**Comment by HowardHub** [comment]
十分感谢！
我刚才也看了一下日志，发现启动失败，出现了以下错误
panic: open chain33.test.toml: no such file or directory
后来我把4个节点的 chain33.toml都改为了 chain33.test.toml，
然后启动成功。

**Comment by YingQm** [comment]
第5步改成了 nohup ./chain33 -f chain33.toml >> log.out 2>&1 &
