### ISSUE TITLE
联盟链隐私数据代理重加密

### ISSUE THREAD

**Issue by jpeng-go** [33cn/chain33#797]
1.  代理重加密技术，实现隐私数据的云端加密存储和动态共享。云服务器存储加密数据，保证数据的隐私，通过代理重加密，用户可在不泄露私钥的情况下将隐私数据动态共享给指定授权人。同时利用秘钥分片算法，最大程度降低代理节点联合授权用户作弊的可能，充分保证用户数据的安全。

2. 代理重加密可以解决联盟链隐私数据加密存储和动态共享。

**Comment by vipwzw** [comment]
这个问题已经解决了吗？

**Comment by jpeng-go** [comment]
> 这个问题已经解决了吗？

已经实现了，issue可以关掉了
