### ISSUE TITLE
p2p dht存在连接节点数过多的问题

### ISSUE THREAD

**Issue by libangzhu** [33cn/chain33#820]
![image](https://user-images.githubusercontent.com/16385190/77985860-1f687380-7348-11ea-8a55-d3070b54f940.png)
需要调整dht相关连接限制

**Comment by vipwzw** [comment]
最大会到多少

**Comment by libangzhu** [comment]
> 最大会到多少

5000多，这样出现5000多个TCP连接

**Comment by vipwzw** [comment]
看看怎么做一个限制

**Comment by libangzhu** [comment]
> 看看怎么做一个限制

嗯，用libp2p-connmanager做管理限制
