### ISSUE TITLE
这两个变量变成可以配置并优化性能

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#822]
https://github.com/33cn/chain33/blob/332df00cc3dfc354f92420b080430ad057afdb06/types/const.go#L154-L157

1. 在blockchain 的内存中，只缓存交易hash，不缓存交易内容。
2. 可以配置的区间不能超过 5000 （low + height）
现在只有120

**Comment by icehawk-hyb** [comment]
目前的代码实现：
1.通过这个结构体缓存最新的区块内容以及交易的hash值
type BlockCache struct {
	cache      map[int64]*list.Element
	cacheHash  map[string]*list.Element
	cacheTxs   map[string]bool
	cacheSize  int64
}
这个缓存的大小是可配置通过defCacheSize值，目前默认是128个区块，也就是缓存128个区块以及交易hash，所以目前AllowPackHeight的区间值是120.小于默认的defCacheSize值。

这个issues是想只缓存指定数量区块的交易hash值，不缓存block信息吗？
还是block信息和交易hash都要一起缓存，缓存5000个block信息以及交易hash可能数据会有点多的。

@vipwzw
