### ISSUE TITLE
单节点性能优化到2万比/s

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#823]
1. 当个节点 solo 模式下面，优化到 2万比/s
2. 测试没个模块的性能以及吞吐量，还有queue的性能。

**Comment by bysomeone** [comment]
#### solo性能测试
##### 环境
xiaomi pro，4核8线程i7-8550u，16g

##### 交易（转账）打包性能

按照功能处理划分，以下为主要耗时部分及对应的粗略值

* 交易签名验证，单核4k/s，多核并发最高，17k/s，单笔60us

* 状态执行，对应ExecBlock，不包含验签，每万笔750ms，单笔75us

* blockchain模块，blockStore.AddTxs，主要是进行交易本地执行，每万笔750ms,  单笔75us

* blockchain模块，blockstore.SaveBlock, 区块数据table化及相关缓存，每万笔200ms，单笔20us

* blockchain模块，blockstore对block数据进行batch写入，每万笔400ms，单笔40us

上述步骤目前是串行执行，即抛开签名验证，目前并发上限约5k/s

##### 其他模块性能统计

* mempool接收交易， 7k/s（包含签名），14k（不包含签名）

* 系统消息队列，消息发送，80w/s

* 交易哈希计算，单笔1us

##### 当前优化

* ExecBlock并行处理，对签名，查重，执行进行并行处理，提升ExecBlock 10%性能

* 单笔交易执行，由于单笔交易耗时已经是微秒级别，且基本是cpu计算型，通过协程并行处理提升效果有限

* loadDriver缓存处理(#830)，单次loadDriver耗时2us，单笔交易执行会多次调用loadDriver。进行缓存处理后，ExecBlock执行时间缩短20%左右


##### 后续优化

* 目前代码在并行处理上，已经很难有优化空间，但整个系统可能存在重复性的cpu计算，例如上述loaddriver，以及交易内部模块流转时，重复性hash计算，Encode等，单个并不耗时，在于数量上可能比较庞大

* 签名+状态执行+本地执行+区块数据存储，实现2w/s不太现实，如果能将任务进行分类，分为链上（签名+状态执行），链下（本地执行+数据存储），应该可以达到比较理想性能

**Comment by vipwzw** [comment]
ExecBlock 和 blockStore.AddTxs （ExecLocal）这两个对于存证数据，执行数据明显偏高。可以用一个相同的账户扣手续费，这样不存在读数据库的情况，就执行，我感觉应该是 1000 ns 以下（存证数据也没有反射）

**Comment by vipwzw** [comment]
反射执行的性能比较低

**Comment by bysomeone** [comment]
none交易AddTxs内部有两个建索引比较耗时

* AddrIndex，交易from，to地址索引，主要提供根据地址查交易的功能，目前支持关闭，每万笔耗时300ms

* TxIndex，交易索引，主要用于外部根据哈希查交易，及内部非TxHeight过期的交易查重，每万笔耗时80ms

* AddrIndex关闭后，nono交易在去验签情况下能接近2w的性能，此时mempool插入交易的性能达到瓶颈

**Comment by vipwzw** [comment]
1. AddrIndex 感觉消耗有点大。
2. 2万比到了，这个基本上问题不大了。
3. TxIndex 在 txheight 开启到情况下，看看能不能做到可选。
4. mempool 看看有没有进一步优化到空间。
5. 分析操作系统级别：IO CPU 内存到使用情况(可以用linux 到性能分析工具)。
6. 能不能形成一套ci，对性能进行测试，对影响性能比较大的pr 进行拒绝操作

**Comment by bysomeone** [comment]
gc简单分析了下，有一些频繁的内存申请或逃逸，可以进行优化，目前暂时分析了两个比较高的

1. leveldb batch set，下源码内部cache不足就会调用grow方法重新分配，目前blockchain存储每万笔none交易的区块，batch大小接近11m，一个区块应该重复分配了很多次，正在找预设置buf的方法

2. 交易签名clone，改成返回值而不是指针应该能解决

**Comment by bysomeone** [comment]
gc方面做了一段时间分析优化，可能有以下几个调整，分别开了issue

* 消息队列NewMessage，热点区域回收 #849
* Transaction扩展增加hash字段 #850
* mempool 性能瓶颈 #851
* 保存leveldb batch使用优化 #852

对gc的优化，主要在于减少系统堆内存申请的大小和次数，从而减少系统内存管理花费cpu时间，包括内存分配，gc过程（对象扫描，标记等），整体上可以提高系统稳定性

**Comment by vipwzw** [comment]
都解决一下，看看能否进一步加快性能

**Comment by bysomeone** [comment]
基本都粗略实现好了，主要看下是否合理，经过测试，效果还是比较明显的

**Comment by bysomeone** [comment]
优化后单机性能应该差不多，后续再测试下c++验签，以及网络部分，网络部分应该瓶颈比较大

**Comment by vipwzw** [comment]
目标已经实现。
