### ISSUE TITLE
p2p minLtBlockTxNum 默认值下，交易多时，传输会阻塞

### ISSUE THREAD

**Issue by wchh** [33cn/chain33#825]
测试2个节点，minLtBlockTxNum默认值为5. 当每秒300个交易的时候，广播区块总是超时。如果屏蔽此功能，比如设置minLtBlockTxNum=10000，当每秒1000比交易的时候，区块也总是及时接收到。

**Comment by bysomeone** [comment]
### 导致原因
* 两个节点的模式，挖矿节点和同步节点在并发数上升后无法保证同样出块速度（挖矿节点执行区块不用验签操作），通常会造成同步节点落后区块，以及mempool无法即时清理，mempool即达到最大容量，通过广播接收的交易基本被丢弃

* minLtBlockTxNum=5时，基本会触发轻广播区块模式，即广播区块内交易哈希，在本地重新组装，在mempool缺失交易情况下，通常会向对端节点请求部分或完整区块，并进行缓存

* 请求过程带来额外的交互，这样轻广播模式反而会降低效率

* 目前轻广播请求过程中需要对区块进行缓存，缓存大小设的太小，ycc出块速度较快，存在缓存满被挤出情况，导致接收到向对端请求的区块后，本地缓存已经清理

### 调整方法

* 轻广播模式区块缓存数调整为可配置

* 局域网模式，不建议使用轻广播

### mempool未满情况
* 由于ycc出块速度较快，局域网两个节点模式，网络通信效率很高，可能存在同一个块的交易还未被添加进本地mempool，已经接收到该区块的广播，触发额外的交互
* 测试未发现网络拥塞情况

@wchh @vipwzw

**Comment by vipwzw** [comment]
@bysomeone  可以吧这个缓存改成 M 数，而不是个数。

**Comment by vipwzw** [comment]
局域网模式 用轻广播应该不至于导致低性能，应该还有其他的原因。

**Comment by bysomeone** [comment]
> 局域网模式 用轻广播应该不至于导致低性能，应该还有其他的原因。

这个问题主要是，mempool来不及清理空间，交易缺失，然后轻广播区块缓存较小，目前是5，容易被挤占，M数指的是空间大小？目前实现是既限定大小也限定空间

**Comment by bysomeone** [comment]
mempool满了导致交易缺失，那轻广播实际上没什么意义，由于是局域网，通信很快并不会降低性能 @vipwzw

**Comment by vipwzw** [comment]
mempool 的设置要保证余量，不会一下子就满了。
