### ISSUE TITLE
rpc: can't find method Chain33.ImportPrivKey

### ISSUE THREAD

**Issue by Adgeros** [33cn/chain33#826]
`rpc` 接口提示这个 `rpc: can't find method Chain33.ImportPrivKey`

**Comment by xies1031** [comment]
![image](https://user-images.githubusercontent.com/44956625/79086496-dadccf00-7d6e-11ea-8f54-f301400ca6a1.png)
这个接口没有问题，你用的是什么版本的节点

**Comment by Adgeros** [comment]
> ![image](https://user-images.githubusercontent.com/44956625/79086496-dadccf00-7d6e-11ea-8f54-f301400ca6a1.png)
> 这个接口没有问题，你用的是什么版本的节点

我是在 mac 下编译的，github下载的 plugin 里面编译的

**Comment by vipwzw** [comment]
注意大小写，key是小写的

**Comment by Adgeros** [comment]
> 注意大小写，key是小写的

明白了，我是用的 [https://www.npmjs.com/package/@33cn/chain33-rpc-api](url) 这个包，请问是你们写的吗，不是的话我自己改了去

**Comment by vipwzw** [comment]
这个我要问一下，你先自己改了吧。

**Comment by Adgeros** [comment]
好的

**Comment by vipwzw** [comment]
chain33-rpc-api  包有问题，要修改，这里先关闭这个issues
