### ISSUE TITLE
Blockchain TestProcessDelBlock 偶发失败

### ISSUE THREAD

**Issue by bysomeone** [33cn/chain33#828]
* ci 错误
```
--- FAIL: TestProcessDelBlock (0.56s)
    chain_test.go:1231: 
        	Error Trace:	chain_test.go:1231
        	Error:      	Received unexpected error:
        	            	ErrBlockHashNoMatch
        	Test:       	TestProcessDelBlock
```

* 相关代码

```go
blockchain/chain_test.go#1231
_, ok, _, err := blockchain.ProcessDelParaChainBlock(true, block, "self", curheight)
require.NoError(t, err)
assert.Equal(t, true, ok)
```

* ci 地址
https://travis-ci.org/github/33cn/chain33/jobs/678535658

**Comment by bysomeone** [comment]
···go
blockchain/chain_test.go#1231
_, ok, _, err := blockchain.ProcessDelParaChainBlock(true, block, "self", curheight)
require.NoError(t, err)
assert.Equal(t, true, ok)
···

**Comment by bysomeone** [comment]
@icehawk-hyb

**Comment by icehawk-hyb** [comment]
[issues828日志.txt](https://github.com/33cn/chain33/files/4522458/issues828.txt)

**Comment by icehawk-hyb** [comment]
通过分析日志，测试ProcessDelParaChainBlock接口删除最新的区块时:
存在GetBlockHeight()获取的是最新区块，
但是在删除时b.bestChain.Tip()中还没有更新成最新的区块,此时会返回ErrBlockHashNoMatch错误信息。修改测试代码返回失败了需要等待一定时间再去调用ProcessDelParaChainBlock接口函数最新区块。
