### ISSUE TITLE
通过系统配置文件修改localdb的version

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#83]
localdb 的version 目前直接写死在代码里面，不够灵活，也不能支持不同的链不同的版本号。
代码在 common/version , 可以把localdb 的version 通过配置文件来配置，这样更加灵活。

**Comment by vipwzw** [comment]
@andyYuanFZM  这个问题南京这边处理一下。

**Comment by andyYuanFZM** [comment]
好的

**Comment by andyYuanFZM** [comment]
@lynAzrael  这个你来改下吧。

**Comment by lynAzrael** [comment]
@andyYuanFZM 好
