### ISSUE TITLE
executor loadDriver cache逻辑错误

### ISSUE THREAD

**Issue by bysomeone** [33cn/chain33#830]
* 代码中loadDriver加了ForkCacheDirver，进行driver缓存，实现上应该是逻辑搞反了

https://github.com/33cn/chain33/blob/69abea8a78b237acf43ee4d46e25d056c0ccf67f/executor/execenv.go#L256

``` go

func (e *executor) loadDriver(tx *types.Transaction, index int) (c drivers.Driver) {
	types.AssertConfig(e.api)
	cfg := e.api.GetConfig()
	if cfg.IsFork(e.height, "ForkCacheDriver") {
		return e.loadDriverNoCache(tx, index)
	}
	return e.loadDriverWithCache(tx, index)
}
```

* Fork之后应该用loadDriverWithCache，fork之前直接loadCache

* 目前交易执行涉及多次loadDriver，修改使用cache后能提高20%性能

* 实现上是否不需要增加 ForkCacheDriver

**Comment by vipwzw** [comment]
这个cache 会产生bug。看看能不能解决这个bug

**Comment by vipwzw** [comment]
和 马登极讨论一下这个问题

**Comment by bysomeone** [comment]
> 和 马登极讨论一下这个问题

好的

**Comment by mdj33** [comment]
https://mainnet.bityuan.com/blockDetail?height=2697584

对于transferToExec这个交易，本来在主链是不允许执行的，由于加了cache，跳过了Allow的检查，就允许执行了。

**Comment by mdj33** [comment]
出错主要有两种场景,以执行器user.p.para.paracross为例
1. 前一条交易的action是allow的，后一条action是notAllow的，后一条需要走none执行器
2. 前一条交易的action是notAllow的，后一条是allow的，前一条是none，后一条需要采用真实执行器
3.前后两条都是allow的或都是notAllow　cache没问题
之前问题主要是cache的执行器没有再调用一下allow，下面的修改看看能不能可不可行
func (e *executor) loadDriverWithCheckCache(tx *types.Transaction, index int) (c drivers.Driver) {
	ename := string(tx.Execer)
	exec, ok := e.execCache[ename]
	if ok && exec.GetName() != "none"{
		if exec.Allow(tx, index) == nil {
			return exec
		}
	}
	exec = drivers.LoadDriverAllow(e.api, tx, index, e.height)
	e.setEnv(exec)
	e.execCache[ename] = exec
	return exec
}

**Comment by bysomeone** [comment]
增加allow逻辑，并且使用cache实现

```go
func (e *executor) loadDriverNew(tx *types.Transaction, index int) (c drivers.Driver) {

	var err error
	ename := string(tx.Execer)
	exec, ok := e.execCache[ename]

	if !ok {
		exec, err = drivers.LoadDriverWithClient(e.api, ename, e.height)
		if err == nil {
			e.execCache[ename] = exec
		}
	}

	if err != nil || exec.Allow(tx, index) != nil {
		exec, _ = e.execCache["none"]
	}else {
		exec.SetEnv(e.height, 0, 0)
		exec.SetName(string(types.GetRealExecName(tx.Execer)))
		exec.SetCurrentExecName(string(tx.Execer))
	}
	e.setEnv(exec)
	return exec
}
```

**Comment by bysomeone** [comment]
* 测试三种情况loaddriver耗时，cache < allow+cache < nocache

* 单个交易在执行期间会多次调用loaddriver，如果能进行复用，也有提升空间

**Comment by vipwzw** [comment]
先 allow+cache 这个模式吧，看看能提升多少
