### ISSUE TITLE
当多次调用 RegisterMineStatusReporter 时，后面会把前面的替换，造成isAutoMinning 判断出错

### ISSUE THREAD

**Issue by wchh** [33cn/chain33#831]
如题。

如果多个挖矿app，多次调用此函数，就会造成前面注册的被后面注册的替换掉。

**Comment by icehawk-hyb** [comment]
分析了一下代码RegisterMineStatusReporter这个接口目前只有ticket和pos33合约的wallet插件会注册。
在wallet模块初始化时会初始化所有已经注册的dapp钱包插件业务。代码如下：
// Init 初始化所有已经注册的钱包业务
func Init(wallet WalletOperate, sub map[string][]byte) {
	for k, v := range PolicyContainer {
		v.Init(wallet, sub[k])
	}
}
此时ticket和pos33的wallet插件会调用RegisterMineStatusReporter挂接各自的处理函数
func (wallet *Wallet) RegisterMineStatusReporter(reporter wcom.MineStatusReport) error {
	if reporter == nil {
		return types.ErrInvalidParam
	}
	if wallet.mineStatusReporter != nil {
		return errors.New("ReporterIsExisted")
	}
	wallet.mineStatusReporter = reporter
	return nil
}

但是wallet模块只会接受最先挂接的钩子函数。如果ticket的wallet 插件先被初始化，就会挂接ticket合约对应的处理函数，pos33的就无法过节。否则就反过来了。但是PolicyContainer 时一个map存储格式，所以每次启动后初始化wallet插件的顺序是不一样的，也就导致每次挂接的处理函数不一样的。
解决方案：
pos33和ticket这种共识合约应该是有排它性的，这种共识合约不能共存。所以在wallet模块初始化wallet插件时需要根据配置的当前共识来排除其他共识对应的wallet插件的。

目前看ticket和pos33有冲突
