### ISSUE TITLE
blockchain 模块批量查询交易信息报错

### ISSUE THREAD

**Issue by hxzqlh** [33cn/chain33#835]
使用 `grpc client` 调用 `d, err := cli.GetTransactionByHashes(context.Background(), &types.ReqHashes{Hashes: hashes})`  批量查询交易信息，报错:

`err="rpc error: code = Internal desc = grpc: error while marshaling: proto: repeated field Txs has nil element"`

假如批量查询100笔，其中只有1笔找不到交易信息，整体也报这个error。如果改成每笔交易都查询一次，效率又太低，很耗资源。

PS： `jsonrpc client` 没有这个情况

**Comment by icehawk-hyb** [comment]
通过分析是grpc在处理数组时有nil时报错导致；
修改方案：在批量获取对应hash的交易不存在时new一个空的结构体即可。

**Comment by vipwzw** [comment]
@icehawk-hyb  你来修改一下吧。
