### ISSUE TITLE
bityuan 真实节点数据量增长比较快的问题

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#838]
在数据库转换后，我们用了这个命令对数据库整体做了压缩。

https://github.com/33cn/chain33/blob/44ee40b75c334bcc88e8889a36ac0af3d4c071e6/blockchain/reduce.go#L53

现在发行，跑一段时间后，数据增长比较快。
1. 测试用 整体 compact 是否可以解决数据量的问题。
2. 直接整体压缩需要时间太长，还会影响性能。找到删除key比较多的区间范围，做compact，看看是否可以解决压缩需求。
3. 在后台跑一个压缩程序，定期压缩。

**Comment by mdj33** [comment]
733w:
10G     ./mavltree/store.db
24G     ./blockchain.db
total:34G
820w:
12G     ./mavltree/store.db
12G     ./mavltree
27G     ./blockchain.db
total:39G

压缩前
root@fzm:~/bityuan/datadir# du -h
12G     ./mavltree/store.db
12G     ./mavltree
27G     ./blockchain.db
39G     .

压缩后:
12G     ./mavltree/store.db
12G     ./mavltree
27G     ./blockchain.db
39G     .
压缩后并没有实际减少
如果一个块平均3k， 100w高度，blockchain.db 增长大概3G是不是差不多的？

**Comment by vipwzw** [comment]
再观察一段时间吧
