### ISSUE TITLE
交易长时间驻留在 mempool 得不到处理

### ISSUE THREAD

**Issue by hxzqlh** [33cn/chain33#839]
```
INFO[05-27|11:12:56] proc msg                                 insId=190768845934913889 orderId=0 hash=dac879143cc58e61705a347e978421a3466eea54d27b28e9a636db62d0fd5332 err=nil 
...
WARN[05-27|11:35:45] retry msg                                times=1 insId=190768845934913889 orderId=0 hash=dac879143cc58e61705a347e978421a3466eea54d27b28e9a636db62d0fd5332 err="rpc error: code = Unknown desc = ErrTxExist"
```

背景：外部的业务系统往节点发交易后，会定期检查该笔交易的执行结果，重试几次仍然获取不到交易的执行结果，便尝试重发该交易（交易hash不变）。

重发后发现节点报错 `ErrTxExist`，是说该笔交易已经在 mempool 中，用命令行去查 `./chain33-cli mempool list` 的确发现在某个节点还保留这些交易，但这笔交易驻留在 mempool 中一直不被打包。

从日志看，其中某笔交易在 mempool 中驻留超过20分钟，与 mempool 的交易清理机制不符。

补充信息：

```
// 构造交易时没有设 expire
tx := &types.Transaction{
		Execer:  []byte(etypes.ExchangeX),
		Payload: types.Encode(xxx),
		Nonce:   rand.NewSource(time.Now().UnixNano()).Int63(),
		To:      address.ExecAddress(etypes.ExchangeX),
	}
```

chain33.toml 配置
```
TxHeight=true 

[mempool]
name="timeline"
poolCacheSize=4000
minTxFee=0
maxTxNumPerAccount=4000

[mempool.sub.timeline]
poolCacheSize=4000
minTxFee=0
maxTxNumPerAccount=4000
```

**Comment by CCCCCDH** [comment]
该问题是经常重发的正常现象，由于没有设置超时时间，超过十分钟的交易已经被mempool清理机制清理了后又重新发进来，误以为没有清理

**Comment by icehawk-hyb** [comment]
此tx-1交易没有被打包可能存在A节点接受到tx-1此交易校验ok之后添加到本节点的mempool中，将此交易广播给其他节点。此交易一直没有被打包可能存在如下情况：
1. 此时打包节点的mempool可能已经满了，此tx-1交易没有被添加到打包节点mempool；
2. 或者是A节点广播给打包节点时由于网络原因tx-1交易被丢失了。
3. 此tx-1交易广播到打包节点了，但是由于本节点交易过多导致此交易没有被及时打包。在mempool中驻留10分钟之后被超时删除了。

根据配置看第一种情况的可能性较大。

**Comment by 33cn** [comment]
以后遇到问题再看吧。先关了这个pr
