### ISSUE TITLE
[chain33-cli] Cli命令根据范围查询区块返回ErrDecode

### ISSUE THREAD

**Issue by andyYuanFZM** [33cn/chain33#84]
新取的plugin代码，编译的chain33-cli
ubuntu@manager:~/game_paraChain$ ./chain33-cli block get -s 1 -e 2
ErrDecode

**Comment by andyYuanFZM** [comment]
@harrylee2015  李海磊帮忙看下。

**Comment by xies1031** [comment]
这个问题 hyb已经修复，还没合并
![image](https://user-images.githubusercontent.com/44956625/48889898-453b5980-ee72-11e8-8e9a-9b6fdc5b89c2.png)
@andyYuanFZM

**Comment by andyYuanFZM** [comment]
好的，那这个我先关了。
