### ISSUE TITLE
允许加载插件的cgo版本

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#844]
https://github.com/33cn/chain33/blob/ffdb5124a2860a8bf6f0b817afc36f2db81df51d/common/crypto/crypto.go#L104

注册的时候，比如ed25519，如果有一个cgo 版本的 加密库就注册成 ed25519_cgo

New 的时候 优先查找 ed25519_cgo 是否存在，如果不存在，那么就查找 ed25519

cgo 版本放在 https://github.com/33cn/plugincgo

**Comment by bysomeone** [comment]
### 调整方法

对于cgo版本注册时，仍然采用相同的name和ty，扩展注册接口，增加是否是cgo版本，内部用两个map区分，New的时候优先获取cgo版本

```go
func Register(name string, driver Crypto, isCGO bool)
```
