### ISSUE TITLE
如果 tx 本身加上了 hash 的cache 这个函数是不是没有必要了。这个就是一个 Tx 的cache 吧。

### ISSUE THREAD

**Issue by 33cn** [33cn/chain33#861]
如果 tx 本身加上了 hash 的cache 这个函数是不是没有必要了。这个就是一个 Tx 的cache 吧。

_Originally posted by @33cn in https://github.com/33cn/chain33/pull/858_

**Comment by 33cn** [comment]
<img width="666" alt="image" src="https://user-images.githubusercontent.com/27620745/84384170-27824080-ac20-11ea-9155-76fb1d864ce6.png">

**Comment by bysomeone** [comment]
txHashCache 统一放在 #899 跟踪
