### ISSUE TITLE
交易检查相关优化方向

### ISSUE THREAD

**Issue by bysomeone** [33cn/chain33#887]
![image](https://user-images.githubusercontent.com/11565373/85945551-3cc1d380-b971-11ea-8355-78d330275ccf.png)

就像我们讨论的那样，如果在此处通过开关控制方便进行评测没有问题，但是后续还是要从整体架构上，在入交易池的地方进行必要的安全检查，然后在后续的执行过程中根据之前的缓存检查结果避免重复检查

_Originally posted by @zhengjunhe in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjczMjIwODc1OnYy/pull_request_review_threads/discussion_

**Comment by bysomeone** [comment]
可以考虑将交易检查进行批量化操作，而不是每次一个新的交易就开启一个新的协程，初始化所有的资源进行检查

_Originally posted by @zhengjunhe in https://github.com/33cn/chain33/pull/858#discussion_r438512074_

**Comment by 33cn** [comment]
批量检查会有性能提升吗？可以测试一下。

**Comment by bysomeone** [comment]
#961 已经对交易重复验签做了优化，其他检查影响不大
