### ISSUE TITLE
通过源码构造交易未判断数值

### ISSUE THREAD

**Issue by xies1031** [33cn/chain33#89]
通过源码构造超过int64上限的交易时，数值错误
![image](https://user-images.githubusercontent.com/44956625/48927945-73be4080-ef15-11e8-85b1-f2376a73528d.png)
@icehawk-hyb

**Comment by 33cn** [comment]
是不是mempool有问题

**Comment by icehawk-hyb** [comment]
mempool这边没有办法检测payload中的amount的值

**Comment by vipwzw** [comment]
已经解决
