### ISSUE TITLE
blockchain 单元测试偶发性错误

### ISSUE THREAD

**Issue by 33cn** [33cn/chain33#894]
https://travis-ci.org/github/33cn/chain33/jobs/703863054

```
INFO[07-01|10:39:22] store close                              module=lognode
--- FAIL: TestBlockTable (1.21s)
    blocktable_test.go:118: 
         Error Trace: blocktable_test.go:118
                         blocktable_test.go:54
         Error:       Not equal: 
                      expected: 6
                      actual  : 7
         Test:        TestBlockTable
    blocktable_test.go:120: title:"user.p.hyb." items:<height:6 hash:"\317'\272,\324\251~#1`<\347\377\242\275\237\266@i\367c\374b\217\241s1\3728\243\355p" > items:<height:5 hash:"\322\202\365e~V \024\310\204\211\262\201\201\254(\372\335\300~jf\037[K6q\353T\365:\256" > items:<height:4 hash:"\273\273\234\237\222]M\225\237\276M\205\313\365\311\003\270\267\221\241\000:X\206\336/\243\322)\205\034I" > items:<height:3 hash:"J\271\217\017\236\264\352\257E\224N\247\246\304\365\371\\M\377\017\202\312M }\355\177^\270\342XH" > items:<height:2 hash:"\235\223t\364\243P=b\006E*\342\270\353H\016\020rw\177\357Z\t.\364\372\371H\307i\022\024" > items:<height:1 hash:"\016\371U\272\241\032d\365o\303\362n\210\306\302\247P\273\354\217\311&\330\0247\362{\313\321\320l\261" > 
    blocktable_test.go:121: {[6 5 4 3 2 1] user.p.hyb. {} [] 0}
    blocktable_test.go:120: title:"user.p.hyb." items:<height:2 hash:"\235\223t\364\243P=b\006E*\342\270\353H\016\020rw\177\357Z\t.\364\372\371H\307i\022\024" > items:<height:1 hash:"\016\371U\272\241\032d\365o\303\362n\210\306\302\247P\273\354\217\311&\330\0247\362{\313\321\320l\261" > 
    blocktable_test.go:121: {[2 1] user.p.hyb. {} [] 0}
```

**Comment by icehawk-hyb** [comment]
issues894&902问题分析：

blockchain TestGetParaTxByTitle 偶发错误 #902
blockchain 单元测试偶发性错误 #894

通过日志分析看这两个测试不过的问题都是由于区块中没有交易引起的。
目前solo是有交易才会出区块的。应该是交易在执行的时候由于某种原因从区块中被删除了，没有Debug日志所以不知道是哪里出错导致交易被删除。
是不是最近有修改过执行区块的流程，应该报错的地方没有报错退出。



issues #894的日志记录：
[32mINFO[0m[07-01|10:39:21] store mavl memset,use preStateHash as stateHash for kvset is null [32mmodule[0m=mavl
[32mINFO[0m[07-01|10:39:21] store mavl commit,do nothing for kvset is null [32mmodule[0m=mavl
[32mINFO[0m[07-01|10:39:21] ExecBlock                                [32mmodule[0m=util [32mheight[0m=7 [32mntx[0m=0 [32mwritebatchsync[0m=true [32mcost[0m=7.893405ms



issues #902的日志记录：
[0m[07-03|09:48:07] store mavl memset,use preStateHash as stateHash for kvset is null [32mmodule[0m=mavl
[32mINFO[0m[07-03|09:48:07] store mavl commit,do nothing for kvset is null [32mmodule[0m=mavl
[32mINFO[0m[07-03|09:48:07] ExecBlock                                [32mmodule[0m=util [32mheight[0m=4 [32mntx[0m=0 [32mwritebatchsync[0m=true [32mcost[0m=4.180635ms

**Comment by icehawk-hyb** [comment]
[issues902日志.txt](https://github.com/33cn/chain33/files/4887968/issues902.txt)
[issues894日志.txt](https://github.com/33cn/chain33/files/4887970/issues894.txt)

**Comment by 33cn** [comment]
除非交易重复了，理论上来说，应该不会删除掉。要么手续费为零了。

**Comment by icehawk-hyb** [comment]
手续费应该不会是0，因为使用同一个地址给别的交易也签名了，出了10个区块，只有其中一个区块没有交易。
