### ISSUE TITLE
crypto 插件支持根据高度使能配置

### ISSUE THREAD

**Issue by bysomeone** [33cn/chain33#897]
目前crypto注册，和高度无关，系统更新时存在fork情况，增加相关支持

* crypto实现调整
* crypto类型更新

**Comment by vipwzw** [comment]
要注意 crypto 的插件目前有两种类型，全局的类型和执行器级别的类型，执行器级别的类型是跟着执行器的，应该是不存在fork的情况。
<img width="723" alt="image" src="https://user-images.githubusercontent.com/1617585/86437462-2f249900-bd37-11ea-853c-64e657d9e249.png">

**Comment by bysomeone** [comment]
1. crypto增加fork高度配置，关键在于增加crypto类型是否使能的检查，暂定方法是在crypto模块自己维护driver fork

```go
//crypto.go

driverForks = make(map[string]int)

func SetDriverFork() {}

func GetDriverFork() {}

```

2. 此处没有和系统 types里面的forks保持兼容，主要是方便在crypto New阶段直接集成使能检查，改动较小，
New函数需要扩展height参数

```go

func New(name string， height int64) (c Crypto, err error) {

     ...
     // check enable
    if height < driverForks[ “name.enable” ] {
             return errors.New("NotEnable")
    }
}
```

3.  执行器级别的crypto driver，获取的时候只是crypto name，最终enable也可以统一限定，是否要限定最后取决于是否需要配置fork


@vipwzw

**Comment by vipwzw** [comment]
这个问题有对应的 pr 吗？

**Comment by bysomeone** [comment]
> 这个问题有对应的 pr 吗？

pr还没提交，代码方面主要是调整New函数，增加height参数
