### ISSUE TITLE
localdb 重新构造速度太慢

### ISSUE THREAD

**Issue by 33cn** [33cn/chain33#91]
localdb在机械硬盘上构造太慢，需要加速，减少刷盘

**Comment by xies1031** [comment]
目前的测试链高度，机械硬盘重新构造一次大概需要20个小时

**Comment by 33cn** [comment]
后面还需要测试一下实际的效果。要等 plugin 更新最新版本

**Comment by xies1031** [comment]
现在新版localdb重构速度显著提升，三个多小时可以完成
