### ISSUE TITLE
下载源代码后，运行make，提示缺少 build.sh,无法完成编译。

### ISSUE THREAD

**Issue by spoonerAhua** [33cn/chain33#918]
下载 release-1.64 分支，然后按照 readme.md 进行操作，运行 make 命令时，提示如下

![image](https://user-images.githubusercontent.com/6853508/89398432-b18fe680-d743-11ea-836c-4df42a233fb9.png)

OS: ubuntu 18.04
go: go1.14.6 linux/amd64

**Comment by spoonerAhua** [comment]
使用master分支的代码，也有相同的现象。

**Comment by bysomeone** [comment]
> 使用master分支的代码，也有相同的现象。

1. build.sh文件位于 chain33/system/dapp/coins/cmd/build.sh，检查环境中是否有sh命令

2. 修改 chain33/system/dapp/coins/cmd/Makefile第三行，使用bash执行 ，再试试make是否可行

    ~~./build.sh $(OUT) $(FLAG)~~ => bash ./build.sh $(OUT) $(FLAG)

**Comment by spoonerAhua** [comment]
thanks
