### ISSUE TITLE
运行提示 panic: open cert.pem: no such file or directory

### ISSUE THREAD

**Issue by spoonerAhua** [33cn/chain33#921]
编译后运行使用命令 【./chain33 -f chain33.toml】运行chain33，提示 【panic: open cert.pem: no such file or directory】
OS：ubuntu 16.04
Branch : master

![image](https://user-images.githubusercontent.com/6853508/89999222-12c63580-dcc1-11ea-87b5-8d2450aa49bc.png)

**Comment by spoonerAhua** [comment]
使用 release-1.64 分支也是相同的提示

**Comment by andyYuanFZM** [comment]
[exec.sub.cert]
# 是否启用证书验证和签名
enable=false    

这个开关是true还是false的？   如果是true的话，需要通过命令行为本节点生成证书文件，  或者把这个开关关闭也可以。

**Comment by 33cn** [comment]
@mdj33  如果证书没有设置，并且rpc 里面的 配置， enableTLS=true，读取证书失败后，提示更加优雅一点。

**Comment by mdj33** [comment]
好， 那现在配置文件缺省还是设成 enableTLS=true 吗   是不是可以缺省false?

**Comment by spoonerAhua** [comment]
设置 enableTLS=false 好用了。
