### ISSUE TITLE
p2p dht 存在协程泄漏

### ISSUE THREAD

**Issue by caopingcp** [33cn/chain33#923]
交易量较大时，p2p 使用 dht 模式存在协程泄漏

复现方法：4个节点的tendermint集群，dht选项下的seeds配置为这4个节点，向每个节点每秒发送2000笔交易，协程数会突然增多
相同环境下，gossip模式没有问题

![image](https://user-images.githubusercontent.com/22811866/90372127-804bda80-e0a2-11ea-9f2e-2db567b57d5b.png)

**Comment by vipwzw** [comment]
后期需要优化 stream
