### ISSUE TITLE
TxHeight 功能不生效

### ISSUE THREAD

**Issue by icehawk-hyb** [33cn/chain33#927]
**Describe the bug**
在如下配置下txheight功能没有生效
Title="chain33"
TestNet=true
FixTime=false
TxHeight=true

[fork.system]
ForkTxHeight=0

**To Reproduce**
如上节点配置即可重现

**Expected behavior**
设置如上配置后，txheight功能生效

**Additional context**

[txheight不生效问题定位分析.txt](https://github.com/33cn/chain33/files/5120999/txheight.txt)

**Comment by 33cn** [comment]
配置TxHeight=true功能不生效问题描述：

一.问题描述：如下配置想使能TxHeight功能，但实际上发现TxHeight功能没有生效
Title="chain33"
TestNet=true
FixTime=false
TxHeight=true

[fork.system]
ForkTxHeight=0


二，问题原因分析：
1，通过打印节点的cfg配置发现，TxHeight的全局配置是false，config.TxHeight配置是true

chainConfig:map[
FixTime:false 
MaxTxFee:1000000000 
MaxTxFeeRate:10000000 
MinBalanceTransfer:0 
MinTxFeeRate:0 
TestNet:true 
TxHeight:false 
cfg.chain33: cfg.local: 
config.FixTime:false 
config.TestNet:true 
config.Title:chain33 
config.TxHeight:true

2.通过查看代码的实现:是通过cfg.IsEnable("TxHeight")接口来判断TxHeight功能是否使能的
而此时是按照TxHeight这个key来查询chainConfig的，此时获取的TxHeight对应的值是false。

3.查看代码中chainConfig配置项的设置。
	在NewChain33Config函数中首先调用setDefaultConfig接口设置默认值，此时有c.S("TxHeight", false)操作
	然后根据配置文件调用chain33CfgInit接口设置，此时判断只有title是“local”时才会设置c.setChainConfig("TxHeight", true)
	
三：测试节点由于交易过期不能同步问题
1.测试节点的配置如下，由于测试节点的Title="local"，所以在chain33CfgInit函数中会设置c.setChainConfig("TxHeight", true)
Title="local"
TestNet=true
FixTime=false
TxHeight=true


2.所以在3117705区块的第一笔交易在正常节点过期时间检测是ok的，由于节点的TxHeight没有生效
3.此交易在测试节点过期时间检测过期，打包此交易的区块高度不在TxHeight功能预设的打包区间

**Comment by 33cn** [comment]
原因是因为目前： TxHeight 还不支持配置
