### ISSUE TITLE
钱包中获取区块是否已经同步处理存在数据DataRace

### ISSUE THREAD

**Issue by chain33-shg** [33cn/chain33#95]
在部分查询通过钱包接口调用钱包中client通道查询信息时，由于其他模块存在多线程调用的场景，所以可能在高频率调用的情况下出现数据竞争问题。

考虑在初始化时增加初始化是否完成的标记，只有初始化完成以后才允许执行一系列操作。

**Comment by vipwzw** [comment]
#96
