### ISSUE TITLE
blockchain 快速同步模式相关问题

### ISSUE THREAD

**Issue by bysomeone** [33cn/chain33#955]
考虑以下场景：

1. blockchain通过快速同步模式，下载某个区块，区块哈希正确情况下，执行失败，如 #895 ，ErrSign错误

2. 重复下载同一高度的正常区块时，由于区块哈希和之前执行失败的一致，直接报ErrBlockExist错误，陷入死循环

3. 由于快速同步模式，已经将错误区块（区块哈希正确）记录在数据库中，重启节点仍然会重新执行该缓存的错误区块，重启节点仍然无法同步

**Comment by icehawk-hyb** [comment]
1.区块hash是区块唯一的标识，必须的保证区块hash一样的情况下，区块内容必定一致。不能保证这个一致性的话，区块hash值唯一性就没有意义了。这个问题的根本原因就是区块hash一样的情况下内容不一样导致的。

2.区块执行失败后，系统会尝试再次从别的节点下载同一高度不同hash的区块来执行，此时是需要一直尝试下载流程没有问题。但是对于下载的区块hash已经在本地就报已经存在不需要再次执行，已经执行失败了，没有必要再去执行一次同一个区块。

3.快速下载是A任务将区块缓存的数据库，B任务从数据库中按照高度读取区块并执行，执行失败的话，就会暂停快速下载并清除快速下载的标记位，然后切换成普通的下载模块，此时会重新从别的节点获取区块，由于再次获取的区块hash已经在 本地执行不过，没有必要再去执行一次同一个区块。

4.重启之后由于上次快速下载的标记位已经被清除，会再次快速下载新的区块的，如果此时能从别的节点下载正确的区块的话，应该是可以执行成功的。

5. 重启之后下载了新的区块还是失败的话，那就是新下载的区块还是错误的。可以尝试多次重启直到下载到正确的区块。除非这个节点连接的都是

6.还有就是通过修改代码每次执行失败就将此区块从缓存中删除，再次下载再次执行。这个修改之后需要做各种场景的测试 @bysomeone @vipwzw

**Comment by bysomeone** [comment]
经过讨论，目前系统已经采用交易fullhash，进行blockhash计算，包含了交易签名，

可能需要保证，tx.sign，tx.checkSign，tx.FullHash这几个接口计算所基于的数据一致
