### ISSUE TITLE
交易签名和验签以及hash计算都应该统一只抽取结构中关心的字段来计算。

### ISSUE THREAD

**Issue by icehawk-hyb** [33cn/chain33#958]
**Describe the bug**
1.目前我们的代码在计算交易hash以及fullhash时只抽取结构中自己关心的字段做计算。
2.而签名和验签是将结构体中不关心的字段置nil来计算的。
3.这两个处理逻辑不一致，导致结构体增加临时字段之后。
    hash计算在新老版本是一样的值（代码实现只抽取了自己关心的字段）。
    而验签的处理时新老版本结果不一样。新版本可以通过代码实现过滤掉不需要关心的字段。
    而老版本的代码会将结构新增加的不识别的字段解析到XXX_unrecognized字段中，此时老板验签就会将XXX_unrecognized字段也计算到眼前数据中，这样就报错了。

我的理解是我们要用于计算的数据要可控，将用于hash计算以及签名的逻辑统一，这样的话要不都出错要不都正确。不会出现这次的hash一致而验签数据不一致的问题。

4. 签名和验签修改成使用cloneTx（）函数只抽取关心的字段，是否会影响验签的性能，可能需要测试看看

@bysomeone @vipwzw

**Comment by vipwzw** [comment]
@bysomeone  你看一下怎么处理比较优雅一点

**Comment by bysomeone** [comment]
> @bysomeone 你看一下怎么处理比较优雅一点

就按照 @icehawk-hyb 的方案改吧，我这边测了性能，影响比较小

**Comment by bysomeone** [comment]
1. 这个方案存在的缺陷是，sign代码可能由第三方实现，无法实时和节点代码同步更新，另外就是后期如需扩展新字段，将引入fork

2. 如果能约定，sign，checksign，fullhash的设计就是要对交易的所有数据做计算（目前是这样的逻辑），这个规则是最简单的，不需要额外维护关心的字段，后期扩展字段不需要fork

3. clonetx之前应该是考虑做Hash()计算时，对protobuf xxx_sizecache的读写会造成冲突，在使用fullhash，且满足2的逻辑，实际上不需要重新拷贝，可以直接对原结构进行Encode，protobuf的Encode是支持并发操作的

4. 如果fullhash不是额外使用clonetx方式去计算，那hashcache问题实际上也能规避，最后在老版本计算出的blockhash是不一致的

@vipwzw

**Comment by 33cn** [comment]
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/27620745/98337215-3e985380-2043-11eb-9ab1-763be426f91c.png">

sign 和 checksign 原来的处理实际上是一样的，并没有什么问题。问题可能是因为 tx的cache 引起的，tx cache 应该只是一个内存计算的优化，不应该保存在硬盘中，而我们encode 的时候，把cache的信息也给encode了。

<img width="360" alt="image" src="https://user-images.githubusercontent.com/27620745/98337541-b8304180-2043-11eb-9b2b-4dcda7ad06a5.png">

**Comment by bysomeone** [comment]
经过讨论，相关接口代码暂时采用原来的逻辑，并移除hash cache相关代码
