### ISSUE TITLE
使用windows solo 模式时，使用 account list 命令查不到 genesis 账号。如何让account list 命令查到 genesis 账号呢？

### ISSUE THREAD

**Issue by spoonerAhua** [33cn/chain33#967]
使用windows solo 模式时，想给其它账号转账，但是发现无法从genesis中转出。
account list 命令查不到 genesis 账号，但是能看到genesis 的余额 。

![image](https://user-images.githubusercontent.com/6853508/101435651-ad6d1300-3947-11eb-96e0-6c6e786e8ad6.png)

**Comment by spoonerAhua** [comment]
并且也能从genesis中转账出去呢？

**Comment by spoonerAhua** [comment]
Title="local"
version="1.64.0-68f55015"

**Comment by xies1031** [comment]
这个地址并不存在于你的wallet中，所以通过account list是无法查询到的
可以通过添加该地址的私钥至wallet的方式，把这个地址加入到钱包里

**Comment by spoonerAhua** [comment]
Thanks! 
需要提前准备好在配置文件中 genesis的私钥，然后启动chain33，再使用account import_key 来导入。
我这样流程对吧？
