### ISSUE TITLE
chain33-cli wallet sign, 无法通过提示信息找到问题。

### ISSUE THREAD

**Issue by spoonerAhua** [33cn/chain33#968]
![image](https://user-images.githubusercontent.com/6853508/101466305-ef17b100-397b-11eb-8831-033ff9dfc536.png)

我想将一段文字写到链上，使用chain33-cli wallet sign，无法通过提示信息找到问题。
能帮忙看看是什么问题么？

**Comment by spoonerAhua** [comment]
chain33-cli wallet sign -a 1CbEVT9RnM5oZhWMj4fxUrJX94VtRotzvs -k 3990969DF92A5914F7B71EEB9A4E58D6E255F32BF042FEA5318FC8B3D50EE6E8 -d "This should be stored"

**Comment by xies1031** [comment]
wallet sign中的-d参数不是用于传递上链信息的。目前是用于交易组签名使用，格式为hex。
上链信息可以选择两种方案：直接在签名中通过备注的方式传递，如使用transfer则为chain33-cli coins transfer -n中添加备注；或编辑为md格式文件，通过chain33-cli exec userdata上传。

**Comment by spoonerAhua** [comment]
thanks!
