### ISSUE TITLE
一条链上的交易可以在另外一条链上执行

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#971]
通过 chain33 搭建的 交易，一条链上的交易，可以在另外一条链上执行。这样比如我两条链上的资产保存在同一个地址中，就会有严重的bug。解决方案可以有两个：

1. 地址的version 每条链可以配置，注意对应的 多重签名地址也要对应的改动。

2. 在transaction交易上专门增加一个字段，表示链的版本，int32的一个数字，可以和p2p 的 channel id 一致，如果版本号不一致，交易将会被拒绝。

**Comment by icehawk-hyb** [comment]
1.只将普通地址的version修改成可配置。
我的理解是多重签名地址就默认version=5不可以配置。这样的话在不同的chain33链只要version是5的都是多重签名地址。
普通地址允许配置成不等于5的version即可。

2.transaction 交易结构体增加channelID也是可以配置的吗？不同的链需要不同的channelID
@vipwzw
