### ISSUE TITLE
[mempool]mempool压满后，再持续发交易，出现panic

### ISSUE THREAD

**Issue by andyYuanFZM** [33cn/chain33#979]
步骤：
1.  mempool size配置 10240 （也可以配小一些，方便复现）
2. 部署4个节点联盟链
2. 持续发存证交易（开启txheight）,把mempool压满。  一会就会出现以下panic  （4个节点都会出现）

153fd92
EROR[01-15|14:38:50] exec tx err                              module=util err="logs:<ty:1 log:\"ErrTxExpire\" > " txhash=0x136b1a2057a25754ddab48e8e1fb0081074588127e71b32ff0759c5f6be9567e
EROR[01-15|14:38:50] exec tx err                              module=util err="logs:<ty:1 log:\"ErrTxExpire\" > " txhash=0x87f9b837f868d62c5504136208c48a88736424ea17fc047d0c06a619c3db20df
EROR[01-15|14:38:50] exec tx err                              module=util err="logs:<ty:1 log:\"ErrTxExpire\" > " txhash=0x2a31bc758dcabe4b66e44f0e997b97d8baf0c4e47094b3b2f05c0a6b4905a4d6
EROR[01-15|14:38:50] exec tx err                              module=util err="logs:<ty:1 log:\"ErrTxExpire\" > " txhash=0x25b980bafe7efc1ab15ad96c532aee35b729092c7870eacc674b3a773e12d9e8
EROR[01-15|14:38:50] exec tx err                              module=util err="logs:<ty:1 log:\"ErrTxExpire\" > " txhash=0x57df61325cd9dbc3ab8e498dc4edda5462ab1398a0bc04c61d127f7a1a953115
panic: interface conversion: interface {} is types.TxHashList, not *types.TxHashList

goroutine 87 [running]:
github.com/33cn/chain33/system/mempool.(*Mempool).eventDelTxList(0xc0001464d0, 0xc071dbf900)
        /home/jpeng/go/pkg/mod/github.com/bysomeone/chain33@v0.0.0-20201026071100-ab0493ff1940/system/mempool/eventprocess.go:145 +0x13d
github.com/33cn/chain33/system/mempool.(*Mempool).eventProcess(0xc0001464d0)
        /home/jpeng/go/pkg/mod/github.com/bysomeone/chain33@v0.0.0-20201026071100-ab0493ff1940/system/mempool/eventprocess.go:89 +0xa91
created by github.com/33cn/chain33/system/mempool.(*Mempool).SetQueueClient
        /home/jpeng/go/pkg/mod/github.com/bysomeone/chain33@v0.0.0-20201026071100-ab0493ff1940/system/mempool/base.go:94 +0x151

**Comment by jpeng-go** [comment]
最新plugin和chain33无法复现，只有chain33_Consortium_1.64.tar.gz版本可以复现

**Comment by andyYuanFZM** [comment]
最新chain33应该已经修复。
