### ISSUE TITLE
这几个配置没有移动到 subconfig (mavl)的

### ISSUE THREAD

**Issue by vipwzw** [33cn/chain33#98]
enableMavlPrefix=false
enableMVCC=false
enableMavlPrune=false
pruneHeight=10000

**Comment by lyh169** [comment]
#`type subConfig struct {
	EnableMavlPrefix bool  `json:"enableMavlPrefix"`
	EnableMVCC       bool  `json:"enableMVCC"`
	EnableMavlPrune  bool  `json:"enableMavlPrune"`
	PruneHeight      int32 `json:"pruneHeight"`
}`
`func New(cfg *types.Store, sub []byte) queue.Module {
	bs := drivers.NewBaseStore(cfg)
	var subcfg subConfig
	if sub != nil {
		types.MustDecode(sub, &subcfg)
	}
	mavls := &Store{bs, make(map[string]*mavl.Tree), nil, subcfg.EnableMavlPrefix, subcfg.EnableMVCC, subcfg.EnableMavlPrune, subcfg.PruneHeight}
	mavls.cache, _ = lru.New(10)
	//使能前缀mavl以及MVCC

	mavls.enableMavlPrefix = subcfg.EnableMavlPrefix
	mavls.enableMVCC = subcfg.EnableMVCC
	mavls.enableMavlPrune = subcfg.EnableMavlPrune
	mavls.pruneHeight = subcfg.PruneHeight
	mavl.EnableMavlPrefix(mavls.enableMavlPrefix)
	mavl.EnableMVCC(mavls.enableMVCC)
	mavl.EnablePrune(mavls.enableMavlPrune)
	mavl.SetPruneHeight(int(mavls.pruneHeight))
	bs.SetChild(mavls)
	return mavls
}`
[store.sub.mavl]
enableMavlPrefix=false
enableMVCC=false
enableMavlPrune=false
pruneHeight=10000
在这个地方使用定义过了，还需要在哪里移动呢？

> enableMavlPrefix=false
> enableMVCC=false
> enableMavlPrune=false
> pruneHeight=10000



> enableMavlPrefix=false
> enableMVCC=false
> enableMavlPrune=false
> pruneHeight=10000

**Comment by lyh169** [comment]
@vipwzw

**Comment by vipwzw** [comment]
o,那可能配置文件没有更新

**Comment by vipwzw** [comment]
#100
