### ISSUE TITLE
blockchain区块batch数据重复写入

### ISSUE THREAD

**Issue by bysomeone** [33cn/chain33#981]
### 问题

1. 目前接口dbMaybeStoreBlock，connectBlock都会将区块数据以batch形式进行写入，数据重复率大概50%
比如5000笔交易区块，单笔交易大小1k，前后两次batch数据量大概分别为6M，12M

2. dbMaybeStoreBlock是基于先将区块暂存的策略，比较适合公链场景下容易出现分叉侧链数据，区块顺序先后等问题，对区块先保存，后组装

3. 联盟链场景下可能不太需要暂存操作，区块通常比较有序，也基本没有分叉情况，如果暂存会增加数据写操作的开销，尤其高并发情况下，影响较大

@vipwzw

**Comment by vipwzw** [comment]
@bysomeone  是否可以考虑 先直接保存区块，而不是临时保存。在公链场景下，看看是否也可以这样。

**Comment by bysomeone** [comment]
fix in #1126 , 通过配置,  区分是否需要回滚, 不回滚情况不需要执行预存储
